// notlar/tarih-1-not.js
window.tarih_1_notlari = [
    "🗺️ <b>TÜRKLEİRİN ANA YURDU:</b> Türklerin ana yurdu Orta Asya’nın üstü Sibirya, sağı Kingan Dağları, solu Hazar Denizi, alt tarafı ise Himalayalardır.",
    "🗣️ <b>TÜRK ADININ ANLAMLARI:</b><br>• <b>Wambery’e göre:</b> 'Türemek'<br>• <b>Kaşgarlı Mahmut’a göre:</b> 'Olgunluk çağı'<br>• <b>Çin kaynaklarına göre:</b> 'Miğfer'<br>• <b>Ziya Gökalp’e göre:</b> 'Kanun, nizam sahibi, töreli'",
    "🏛️ <b>ORTA ASYA KÜLTÜR MERKEZLERİ:</b><br>• <b>Anav:</b> En eski kültür merkezi<br>• <b>Afanesyevo:</b> En eski Türk kültür merkezi<br>• <b>Tagar:</b> En gelişmiş kültür merkezi<br>• <b>Karasuk:</b> Demirin işlendiği ilk yer<br>• <b>Kelteminar:</b> Yerleşik yaşamın görüldüğü ilk yer",
    "📜 <b>İLK KAYITLAR:</b> Türk adı ilk olarak <b>Çin kaynaklarında</b> geçer. İlk defa devlet ismi olarak <b>Göktürk Devleti</b> kullanmıştır. Türkiye adı ilk defa <b>Bizans kaynaklarında</b> geçmiştir.",
    "🏹 <b>TÜRK GÖÇLERİNİN NEDENLERİ:</b> Kuraklık, kıtlık, iklimin tarım ve hayvancılığa elverişsiz olması, Çin, Kitan ve Moğol baskısı, boylar arası mücadele, hayvan hastalıkları ve yeni yerler görme isteği.",
    "🌍 <b>TÜRK GÖÇLERİNİN SONUÇLARI:</b> Türk kültürü geniş alanlara yayıldı. Türklerin din ve dil yapıları değişti. Türk tarihini bir bütün içinde incelemek zorlaştı.",
    "🛡️ <b>İSKİTLER (SAKALAR):</b> Türk adını İranlılar vermiştir. Bilinen <b>ilk Türk boyudur.</b> En önemli destanları <i>Alp Er Tunga Destanı</i>'dır. Perslerle yaptığı mücadele <b>Şehname’ye (Afrasiyab)</b> konu olmuştur. Kadın hükümdarı <b>Tomris Hatun</b>'dur. Amazon adı verilen kadın savaşçıları vardır. Atı evcilleştirip <b>üzengiyi ilk defa</b> kullandılar. Maden işinde ustalaştıkları için <b>'Bozkırın Kuyumcuları'</b> unvanını almışlardır.",
    "🐎 <b>ASYA HUN DEVLETİ (BÜYÜK HUN DEVLETİ):</b> Bilinen <b>ilk Türk devletidir.</b> Kurucusu <b>Teoman</b>, başkenti <b>Ötüken</b>'dir. En önemli hükümdarı <b>Mete Han</b>'dır.",
    "👑 <b>METE HAN DÖNEMİ:</b> Vatan sevgisinden bahseden ilk hükümdardır. 26 Türk kavmini toplayıp Orta Asya’da ilk defa <b>Türk siyasi birliğini</b> sağlamıştır. Orduda <b>onlu sistemi</b> kurmuştur. Mete Han’dan sonra Hohanyeh tahta geçti. Çin istilası ve iç mücadelelerle devlet ikiye ayrıldı. İlk milliyetçi kişi olarak <b>Çiçi</b>: <i>'İstiklali feda etmeyi gülünç ve utanç verici buluyorum.'</i> demiştir. Çin baskısıyla Balamir önderliğinde batıya göç edilmesi <b>Kavimler Göçü’ne</b> sebep olmuştur.",
    "🌪️ <b>KAVIMLER GÖÇÜ SONUÇLARI:</b> Roma ikiye ayrıldı. Avrupa’da Avrupa Hun Devleti kuruldu. Avrupa’da <b>feodalite (derebeylik)</b> ortaya çıktı. Kilise güçlendi ve <b>skolastik düşünce</b> doğdu. Yeni Avrupa milletleri ortaya çıktı. İlk Çağ kapandı, Orta Çağ açıldı.",
    "🇪🇺 <b>AVRUPA HUN DEVLETİ:</b> Kurucusu <b>Balamir</b>'dir. Macaristan’da kuruldu. <b>Uldız</b>, Bizans elçisine: <i>'İstersem güneşin battığı yere kadar her yeri zapt ederim.'</i> demiştir. En parlak zamanı <b>Attila</b> dönemidir. Bizans ile <b>Margos ve Anatolios</b> antlaşmaları yapılarak Bizans vergiye bağlanmıştır. Papa'nın ricası, Roma'nın kutsal sayılması ve Sasani seferi isteğiyle Attila Batı Roma'dan vazgeçmiştir. Attila; <b>'Tanrının Kırbacı', 'Etzel' ve 'Cesur kavimlerin efendisi'</b> olarak bilinir.",
    "⚔️ <b>AVRUPA'YA GÖÇ EDEN DİĞER TÜRK BOYLARI:</b><br>• <b>Avarlar:</b> Kurucusu Bayan Han'dır. Çin'de 'Juan Juan', Göktürklerde 'Apar' denir. Sasanilerle birlikte <b>İstanbul’u kuşatan ilk Türk devletidir.</b><br>• <b>Uzlar:</b> Hristiyan Oğuzlardır. Bizans'ta ücretli askerlik yapıp Malazgirt'te taraf değiştirdiler.<br>• <b>Peçenekler:</b> Tarih boyunca devlet kuramadılar, boy halinde yaşadılar.<br>• <b>Macarlar:</b> Soylarını Attila’ya dayandırırlar.<br>• <b>Bulgarlar:</b> Tuna (Hristiyan, Çar unvanı) ve İtil (Müslüman, İlteber Almış Han) olarak ikiye ayrıldılar. <b>İtil Bulgarları ilk Müslüman Türk devletidir.</b><br>• <b>Hazarlar:</b> Museviliği kabul eden <b>ilk ve tek</b> Türk devletidir. <b>Ordusuna ücretli asker alan ilk ve tek</b> Türk devletidir. Yaşadıkları döneme 'Pax Hazaria' denir. 7 hakimden oluşan Hakimler Heyeti vardır.<br>• <b>Sibirler:</b> 'Yoldan sapan, serbest dolaşan' anlamına gelir.<br>• <b>Kıpçaklar (Kumanlar):</b> Yaşadıkları yere Deşt-i Kıpçak denir. Dede Korkut Hikâyeleri’ne ve Rusların İgor Destanı’na konu olmuşlardır.",
    "📐 <b>I. GÖKTÜRK DEVLETİ:</b> Aşina boyuna mensupturlar. <b>Türk adıyla kurulan ilk Türk devletidir.</b> Kurucusu <b>Bumin Kağan (İl Kağan)</b>'dır. En parlak dönemi <b>Mukan Kağan</b>'dır. Bizans'a ilk elçi gönderen devlettir. Topo Kağan Budizm'i seçince halkla arası açılmıştır. Çin esaretine karşı ilk milli istiklal ayaklanmasını <b>639'da Kürşad</b> başlatmıştır.",
    "🏛️ <b>II. GÖKTÜRK (KUTLUK) DEVLETİ:</b> Kurucusu <b>Kutluk Kağan (İlteriş)</b>'dır. Merkezi Ötüken'dir. Vezir <b>Tonyukuk 'Türklerin Bismarck'ı'</b> olarak bilinir ve ilk Türk tarihçisidir. Bilge Kağan'ın şehirleri surlarla çevirme (kale içine yerleşme) teklifini Tonyukuk reddetmiştir. Basmiller, Karluklar ve Uygurlar birleşerek bu devlete son vermiştir.",
    "🌾 <b>UYGURLAR:</b> 'Akraba, müttefik' demektir. Kurucusu Kutluk Bilge Kül Kağan'dır. Merkez Ötüken'den Karabalgasun'a taşındı. <b>Bögü Kağan</b> döneminde <b>Maniheizm</b> kabul edildi. <b>Yerleşik yaşama geçen ilk Türk devletidir.</b> Resim (Fresko-Duvar resmi), minyatür, kütüphane, orta oyunu (tiyatro) ve bankacılık gelişti. Ressamlara <b>Bedizci</b> denir. Kırgızlar son vermiştir. Moğollar onlara 'Benim hocam' demiştir.",
    "🌍 <b>ORTA ASYA'DAKİ DİĞER BOYLAR:</b><br>• <b>Kırgızlar:</b> Manas Destanı ve Yenisey Kitabeleri onlara aittir. Cengiz Han’a itaat eden ilk Türk topluluğudur.<br>• <b>Karluklar:</b> <b>İslamiyet’i kabul eden ilk Türk topluluğudur.</b> Talas Savaşı'nda Abbasileri desteklediler.<br>• <b>Türgişler:</b> Hükümdarı <b>Baga Tarkan kendi adına para bastıran ilk Türk hükümdardır.</b> Sulu Kağan Emevi ilerleyişini durdurmuştur.<br>• <b>Akhunlar (Eftalitler):</b> Mazdek İsyanı'nı bastırdılar. Göktürk-Sasani iş birliğiyle yıkıldılar.<br>• <b>Oğuzlar:</b> Selçuklu ve Osmanlı'yı kuran en kalabalık Türk boyudur.",
    "⚖️ <b>DEVLET VE TOPLUM YAPISI:</b><br>• <b>Kavramlar:</b> Kün (Halk), Oksızlık (Bağımsızlık), Ayuki (Hükümet), Aygucu (Vezir), Buyruk (Bakan), Tudun (Vergi memuru), Tutuk (Askerî vali), Tigin (Hükümdar oğlu), İnanç (Lala), Şad (Hanedan üyesi komutan), Bitikçi (Katip).<br>• <b>Gök Tanrı Yetkileri:</b> Kut (Siyasi-Yönetme gücü), Küç (Askeri güç), Ülüş (Ekonomik pay).<br>• <b>Toplumsal Sıralama:</b> Oguş (Aile) → Urug (Sülale) → Boy → Budun (Millet) → İl (Devlet).<br>• <b>Tüz:</b> Devlet ile vatandaşın karşılıklı yazısız sözleşmesi.<br>• <b>Yelme:</b> Öncü keşif ve istihbarat akınları.",
    "📋 <b>KURULTAY VE MECLİSLER:</b> Danışma meclisidir, üyelerine <b>Toygun</b> denir. Hatun (Hükümdar eşi) kurultaya katılır, elçi kabul eder. Diğer meclisler: Tabgaçlar (Nazırlar), Hazarlar (İhtiyarlar), Peçenekler (Komenton), Tuna Bulgarları (Millet), Avrupa Hunları (Seçkinler). İkili teşkilatta Doğu'da Kağan, Batı'da Yabgu (kardeş) bulunur.",
    "📆 <b>KÜLTÜR, İNANÇ VE SANAT:</b> Törenin 4 değişmez kuralı: Könilik (Adalet), Uzluk (İyilik), Tüzlük (Eşitlik), Kişilik (İnsanlık).<br>• <b>Kullanılan Takvimler:</b> 12 Hayvanlı, Hicri, Celali, Rumi, Miladi.<br>• <b>İnanç Terimleri:</b> Yuğ (Cenaze), Kurgan (Mezar), Balbal (Mezar taşı), Tamu (Cehennem), Uçmağ (Cennet), Yarlığ (Hakanın emri). Pazırık Halısı ve Altın Elbiseli Adam önemli eserlerdir. Mangala 48 taşla oynanan zeka oyunudur."
];