// notlar/cografya-4-not.js
window.cografya_4_notlari = [
    "⛰️ <b>TÜRKİYE'NİN PLATOLARI:</b> Çevresine göre yüksekte kalan, akarsular tarafından derince yarılmış geniş düzlüklere plato adı verilir. Ülkemizde platoların geniş yer kaplaması, Anadolu'nun 4. Jeolojik Zaman'da (Kuvaterner) epirojenez ile <b>toptan yükseldiğinin</b> en büyük kanıtıdır.",
    "🦎 <b>1. KARSTİK PLATOLAR (Teke ve Taşeli):</b> Akdeniz Bölgesi'nde yer alan, kireç taşlarının (kalker) erimesiyle oluşmuş engebeli platolardır.<br>• Su yer altına sızdığı için yüzeyde su kıttır.<br>• Toprak verimsiz (Terra-Rossa) olduğu için <b>tarım gelişmemiştir.</b><br>• Engebeli yapıdan dolayı <b>nüfus azdır.</b><br>• Maki bitki örtüsüne bağlı olarak <b>kıl keçisi yetiştiriciliği</b> en önemli hayvancılık faaliyetidir.",
    "🌋 <b>2. VOLKANİK (LAV ÖRTÜSÜ) PLATOLAR:</b> Magmadan çıkan lavların çöküntü alanlarını doldurması ve ardından akarsularca yarılmasıyla oluşan platolardır. Doğu Anadolu ve İç Anadolu'da görülür.",
    "❄️ <b>ERZURUM-KARS VE ARDAHAN PLATOLARI:</b> Türkiye'nin en karakteristik volkanik platolarıdır.<br>• <b>Yükseklik:</b> Türkiye'nin en yüksek platolarıdır.<br>• <b>İklim:</b> Sert karasal iklim görülür, kışlar çok uzun ve soğuktur.<br>• <b>Yağış:</b> En fazla yağışı <b>yaz mevsiminde (yaz yağışları)</b> alır.<br>• <b>Bitki Örtüsü:</b> Yaz yağışlarıyla yeşeren gür <b>çayır bitki örtüsü</b> hakimdir.<br>• <b>Ekonomi:</b> Çayırlara bağlı olarak <b>büyükbaş mera hayvancılığı</b> ve buna paralel olarak <b>et-süt sanayisi</b> çok gelişmiştir. Tarımsal faaliyetler ise sıcaklık düşüklüğünden dolayı çok azdır.",
    "🎈 <b>KAPADOKYA VE KİRŞEHİR PLATOLARI:</b><br>• <b>Kapadokya Platosu:</b> Nevşehir çevresindeki volkanik tüflerin aşınmasıyla oluşmuştur. Peri bacaları sayesinde <b>turizme büyük fayda</b> sağlar.<br>• <b>Kırşehir Platosu:</b> Volkanik ve dalgalı düzlük yapısına sahip olup, üzerinde <b>tarım</b> yapılabilen platolarımızdandır.",
    "🏭 <b>3. AŞINIM DÜZLÜĞÜ PLATOLARI (Çatalca-Kocaeli ve Perşembe):</b> Dağlık ve engebeli alanların dış kuvvetler tarafından milyonlarca yıl boyunca aşındırılarak deniz seviyesine yakın bir düzlük haline getirilmesiyle oluşurlar.",
    "🌉 <b>ÇATALCA-KOCAELİ PLATOSU (Marmara):</b> İstanbul ve Kocaeli'yi içine alan, Türkiye'nin ekonomik kalbidir.<br>• <b>Yükseklik:</b> Ortalama yükseltisi <b>en alçak</b> olan platodur.<br>• <b>Gelişmişlik:</b> Sanayi, ticaret ve nüfus bakımından <b>en gelişmiş</b> platodur.<br>• <b>Ekonomi:</b> Yoğun kentleşme ve sanayiden dolayı bu platoda <b>tarım ve hayvancılık faaliyetleri oldukça azdır.</b>",
    "🥝 <b>PERŞEMBE PLATOSU (Ordu - Karadeniz):</b> Karadeniz Bölgesi'nde yer alan bir aşınım platosudur. Çatalca-Kocaeli'nin aksine yeşil doğası korunmuş olup, üzerinde aktif olarak <b>tarım faaliyetleri</b> yapılmaktadır.",
    "🌾 <b>4. TABAKA DÜZLÜĞÜ (YATAY DURUŞLU) PLATOLARI:</b> Sert tabakaların yatay duruşlu olduğu, karasal iklimin hüküm sürdüğü iç bölgelerdeki geniş düzlüklerdir.<br>• <b>Başlıca Platolar:</b> Bozok (Yozgat), Haymana (Ankara), Cihanbeyli (Konya), Obruk (Konya), Uzunyayla (Sivas-Kayseri arası), Yazılıkaya (Eskişehir-Afyon arası), Gaziantep ve Şanlıurfa platoları.<br>• <b>İklim ve Bitki Örtüsü:</b> Tamamında <b>Karasal İklim</b> ve ilkbahar yağışlarıyla yeşeren <b>bozkır (step) bitki örtüsü</b> hakimdir.<br>• <b>Tarım:</b> İklim şartlarına bağlı olarak kuru tarım yöntemiyle yoğun şekilde <b>tahıl tarımı (buğday, arpa)</b> yapılır.<br>• <b>Hayvancılık:</b> Bozkır bitki örtüsünün cılız otlarından dolayı <b>küçükbaş hayvan (koyun) yetiştiriciliği</b> çok yaygındır."
];