// notlar/cografya-6-not.js
window.cografya_6_notlari = [
    "💧 <b>TÜRKİYE'DE AKARSULARIN OLUŞTURDUĞU YER ŞEKİLLERİ:</b> Akarsular topoğrafyayı şekillendirirken güçlerine ve arazinin yapısına göre <b>Aşındırma</b>, <b>Biriktirme</b> ya da <b>Hem Aşındırma Hem Biriktirme</b> şekilleri oluştururlar.",
    "⛰️ <b>AŞINDIRMA ŞEKİLLERİ (Genel Liste):</b> Kırık Bayır (Badlands), Peri Bacası, Plato, Şelale, Dev Kazanı, Aşınım Düzlüğü (Peneplen) ve Vadi türleri akarsu aşındırma faaliyetleri sonucunda meydana gelir.",
    "🌵 <b>1. KIRIK BAYIR (Badlands):</b> Bitki örtüsünden yoksun, kurak ve yarı kurak yamaçlarda sel sularının toprağı ve ana kayayı derince yararak oluşturduğu pürüzlü yamaçlardır. Türkiye'de en net örnekleri <b>İç Anadolu</b> ve <b>Güneydoğu Anadolu</b> bölgelerinde görülür.",
    "🌋 <b>2. PERI BACALARI:</b><br>• <b>Nevşehir (Kapadokya) Peri Bacaları:</b> Oluşumunda <u>volkanizma</u> (iç kuvvet/tüf-bazalt), <u>akarsu aşındırması</u> (dış kuvvet/asıl şekillendirici) ve dolaylı olarak <u>rüzgar</u> etkisi rol oynamıştır.<br>• <b>Erzurum (Narman) Peri Bacaları:</b> Erzurum Narlı'da bulunur. Nevşehir'den farkı, volkanik değil <u>kumtaşının</u> (tortul kayaçların) su tarafından aşındırılmasıyla oluşmuş olmasıdır.",
    "🌊 <b>3. ŞELALE (Çağlayan) VE DEV KAZANI:</b> Akarsu yatağındaki eğim kırıklığının olduğu dikliklerde şelaleler oluşur. Şelalelerin yüksekten döküldüğü (döküldüğü yerlerdeki) çukurlara ise <b>dev kazanı</b> denir.<br>📌 <b>Başlıca Şelalelerimiz:</b> Manavgat (Antalya), Düden (Antalya), Girlevik (Erzincan), Tortum (Erzurum), Tatlıca (Sinop), Muradiye (Van).",
    "🌍 <b>4. AŞINIM DÜZLÜĞÜ (Peneplen):</b> Akarsu aşındırmasının en son halidir. Bir arazinin deniz seviyesine yakın, çok hafif engebeye sahip olması durumudur. Türkiye yakın bir jeolojik zamanda toptan yükseldiği için ülkemizde tam anlamıyla <b>yoktur</b>.",
    "📐 <b>5. VADI:</b> Bir akarsuyun kaynak noktası ile denize döküldüğü ağız kısmı arasındaki yapısına vadi denir.<br>• <b>Çentik Vadi (V Şekilli Vadi):</b> Vadi tabanı yoktur. Derin vadilerdir, bu yüzden tarım alanları dardır ve akarsu derinde aktığı için <u>taşkın riski düşüktür</u>. 📌 <i>Yükseltinin fazla olduğu yerlerde bulunur.</i>",
    "🛣️ <b>5. VADİ TÜRLERİ (Boğaz Vadi):</b> Dağları enine yarıp geçen vadilerdir. Kızılırmak, Sakarya, Fırat ve Dicle yataklarında görülür. Doğal birer geçit olduklarından <u>yol yapımı kolaydır ve kıyıdan iç kesimlere olan ulaşımı kolaylaştırır</u>. 📌 <i>Kıyıya paralel dağları aşan akarsularda (Seyhan-Ceyhan, Kızılırmak-Yeşilırmak) boğaz vadisi bulunur.</i>",
    "🏜️ <b>5. VADİ TÜRLERİ (Kanyon ve Geniş Tabanlı Vadi):</b><br>• <b>Kanyon Vadi:</b> Farklı dirençteki kayaçların basamak basamak aşınmasıyla oluşan dik yamaçlı vadilerdir. 📌 <i>Karstik arazilerde bulunur ve Türkiye'de karstik Akdeniz tarafında yaygındır.</i><br>• <b>Geniş Tabanlı Vadi:</b> Eğimin azaldığı yerlerde suların derine aşındırması biter, ancak yana doğru aşındırmaya başlar. 📌 <i>Geniş tabanlı vadiler Ege'de yaygın olarak bulunur.</i>",
    "🌾 <b>BİRİKTİRME ŞEKİLLERİ (Genel Liste):</b> Akarsuyun taşıma gücünün azaldığı yerlerde taşıdığı malzemeleri biriktirmesiyle oluşur. Irmak Adası, Birikinti Konisi ve Yelpazesi, Dağ Eteği Ovası, Dağ İçi Ovası ve Delta Ovası başlıca biriktirme şekilleridir.",
    "📐 <b>BİRİKTİRME ŞEKİLLERİ (Detaylar):</b><br>• <b>Birikinti Konisi ve Yelpazesi:</b> Dağların içinden kum, çakıl gelip bütün malzemeyi aşağı sarmarsa birikinti konisi; bu malzeme genişlerse birikinti yelpazesi olur. 📌 <i>Aydın şehri belirgin bir birikinti üzerine kurulmuştur.</i><br>• <b>Dağ Eteği ve Dağ İçi Ovası:</b> Yan yana gelen birikintilerin dağ eteğinde birleşmesiyle dağ eteği ovası oluşur. En net örneği: <u>Uludağ eteğindeki Bursa Ovası</u>'dır. Dağların arasında kalan düzlüklerdeki birikmeler ise dağ içi ovalarını oluşturur.<br>• <b>Irmak Adası (Kum Adası):</b> Eğimin azaldığı yataklarda, akarsuyun yatak ortasında milleri adacıklar şeklinde biriktirmesidir.",
    "📐 <b>DELTA OVASI OLUŞUM ŞARTLARI:</b> Akarsuların denize döküldüğü yerlerde yapmış olduğu biçimindeki ovalardır. Bir yerde delta oluşabilmesi için <b>kıta sahanlığı geniş olmalı</b> (deniz sığ olmalı). Dağların kıyıya uzanışı dik ise (Ege) kıta sahanlığı geniş, paralel ise (Karadeniz-Akdeniz) kıta sahanlığı dardır (istisnalar hariç).",
    "🔄 <b>HEM AŞINDIRMA HEM BİRİKTİRME ŞEKİLLERİ:</b><br>• <b>Menderes:</b> Büklüm. Eğim az, yana aşındırma fazladır, taşıma ise azdır. Akarsu yatağında 'S' harfi çizer.<br>• <b>Seki:</b> Taraça. Alüvyonlu vadi tabanına sahip bir akarsuyun yeniden derine doğru aşındırmasıyla oluşan basamaklı şekillerdir."
];