// notlar/cografya-10-not.js
window.cografya_10_notlari = [
    "🌊 <b>TÜRKİYE'DE KIYI ŞEKİLLENMESİ (Genel Özellikler):</b> Kıyılarımızın şekillenmesinde en temel dış kuvvet <b>dalgalar ve akıntılardır</b>. Dalgalar dağların kıyıya paralel ve dik olduğu yamaçlarda <u>aşındırma</u>, deniz derinliğinin az olduğu sığ kıyılarda ise <u>biriktirme</u> yapar. Ayrıca kıyı şekillenmesinde akarsular, rüzgarlar, dağların uzanış doğrultusu ve epirojenez (kıta oluşumu) de doğrudan etkilidir.",
    "📐 <b>DALGA AŞINDIRMA ŞEKİLLERİ:</b><br>• <b>Falez (Yalıyar):</b> Dağların kıyıya paralel ve hemen kıyıdan başladığı yerlerde, dalgaların çarpması sonucu kıyının alt kısmının oyulması ve üst kısmın çökmesiyle oluşan dik uçurumlardır. 📌 <i>Türkiye'de en net görüldüğü yerler: <u>Doğu Karadeniz</u>, <u>Batı Karadeniz</u>, <u>Antalya kıyıları</u> ve <u>Marmara'da Yıldız Dağları (Istranca) kıyıları</u>dır.</i><br>• <b>Aşınım Platoları:</b> Falezler ile deniz arasında zamanla dalga aşındırması sonucu oluşan düzlüklerdir.",
    "⚠️ <b>HAYATİ SINAV NOTU (Falez - Delta İlişkisi):</b> Bir kıyıda <b>Delta Ovası varsa orada kesinlikle falez OLMAZ</b>; aynı şekilde falez olan dik kıyılarda da delta ovası oluşamaz! Çünkü delta sığ kıyılarda, falez ise derin ve dik kıyılarda meydana gelir.",
    "🏖️ <b>DALGA BİRİKTİRME ŞEKİLLERİ:</b> Deniz derinliğinin az (sığ), kıta sahanlığının geniş olduğu yerlerde dalgaların taşıdığı kumları yığmasıyla oluşur.<br>• <b>Plaj (Kumsal):</b> Dalgaların getirdiği kumların kıyıda şerit halinde birikmesidir.<br>• <b>Kıyı Oku:</b> Dalga ve akıntıların taşıdığı kumları kıyıdan denize doğru bir ok şeklinde uzatmasıdır.<br>• <b>Kıyı Kordonu:</b> Kıyı oklarının büyüyerek bir koy veya körfezin önünü neredeyse tamamen kapatacak şekilde uzanmasıdır.",
    "🏝️ <b>DALGA BİRİKTİRME ŞEKİLLERİ (Lagün ve Tombolo):</b><br>• <b>Lagün (Deniz Kulağı):</b> Kıyı oklarının veya kordonlarının bir koyun önünü tamamen kapatmasıyla koyun göle dönüşmesidir (Fethiye Ölüdeniz, Durusu/Terkos, Büyük ve Küçük Çekmece gölleri bu mantıktadır).<br>• <b>Tombolo (Saplıada):</b> Kıyıya yakın bir adanın, dalgaların biriktirdiği kumlar (kıyı oku) vasıtasıyla karaya bağlanarak bir yarımadaya dönüşmesidir. 📌 <i>Türkiye'deki en net ve klasik örneği Balıkesir'deki <u>Kapıdağ Yarımadası</u>'dır. Sinop İnceburun da bir diğer örnektir.</i>",
    "🗺️ <b>TÜRKİYE'DE GÖRÜLEN KIYI TİPLERİ:</b><br>• <b>Dalmaçya Kıyı Tipi:</b> Dağların kıyıya paralel uzandığı yerlerde, deniz seviyesinin yükselmesiyle dağlar arasındaki vadilerin sular altında kalması ve dağların zirvelerinin kıyıda irili ufaklı adacıklar şeklinde görünmesidir. 📌 <i>Türkiye'deki tek ve en net yeri: <u>Teke Yarımadası'nın güneyi (Finike ile Kaş arası)</u> kıyılarıdır.</i>",
    "🗺️ <b>TÜRKİYE'DE GÖRÜLEN KIYI TİPLERİ (Ria ve Kalanlı Kıyı):</b><br>• <b>Ria Kıyı Tipi:</b> Deniz seviyesinin yükselmesi veya kıyı kesimindeki toprakların epirojenezle çökmesi sonucu, denize dik uzanan <u>eski akarsu vadilerinin</u> sular altında kalmasıyla oluşan girintili çıkıntılı kıyılardır. 📌 <i>En belirgin örnekleri: <u>İstanbul Boğazı</u>, <u>Çanakkale Boğazı</u>, Haliç ve Muğla'daki <u>Gökova Körfezi</u> kıyılarıdır.</i><br>• <b>Kalanlı Kıyı Tipi:</b> Karstik akarsu vadilerinin ve kanyonlarının sular altında kalmasıyla oluşan özel kıyı şeklidir. 📌 <i>Türkiye'de <u>Mersin - Silifke kıyıları</u> buna en net örnektir.</i>"
];