// notlar/cografya-3-not.js
window.cografya_3_notlari = [
    "🌪️ <b>2. DIŞ KUVVETLER:</b> Kaynağını atmosferdeki hava olaylarından ve enerjisini Güneş'ten alan kuvvetlere dış kuvvetler denir. Yeryüzünü aşındırma, taşıma ve biriktirme faaliyetleriyle şekillendirirler.",
    "💧 <b>DIŞ KUVVETLERİN TÜRKİYE'DEKİ ETKİLERİ:</b><br>• Türkiye'nin bugünkü yeryüzü görünümüne gelmesinde <b>en etkili dış kuvvet akarsulardır.</b><br>• Kurak ve yarı kurak iklim bölgelerinde (İç Anadolu ve Güneydoğu) en etkili dış kuvvet <b>rüzgarlardır.</b><br>• Kıyıların şekillenmesinde en büyük pay <b>dalga ve akıntılara</b> aittir.<br>• Karstik sahalarda (Akdeniz Bölgesi) <b>yer altı suları</b> şekillendirmede etkilidir.<br>• <b>Buzullar</b>, Türkiye'nin matematik konumundan (orta kuşakta yer almasından) dolayı şekillenmede <b>en az etkili dış kuvvettir.</b>",
    "⏳ <b>B. TÜRKİYE'DE JEOLOJİK ZAMANLAR (1. JEOLOJİK ZAMAN - PALEOZOİK):</b> Bu dönemde oluşan <b>masif araziler</b>; milyonlarca yıl önce katılaşmış, sıkışmış, sert ve yaşlı temel bloklardır. Jeolojik olarak oturmuş yapılara sahip olduklarından, kural olarak iç kısımlarında <b>deprem riski azdır</b> ve Türkiye'nin temel iskeletini oluştururlar.",
    "🗺️ <b>TÜRKİYE'DEKİ EN BİLİNEN MASİF ALANLARI:</b><br>• <b>Yıldız Dağları Masifi:</b> Trakya (Haritanın kuzeybatısı)<br>• <b>Kastamonu Masifi:</b> Batı Karadeniz<br>• <b>Menteşe Masifi:</b> Ege'nin güneybatısı<br>• <b>Taşeli Masifi:</b> Akdeniz'in güney çıkıntısı (Teke-Taşeli)<br>• <b>Bitlis Masifi:</b> Doğu Anadolu<br>• <b>Mardin Masifi:</b> Güneydoğu sınırı",
    "🦕 <b>2. JEOLOJİK ZAMAN (MEZOZOİK):</b> Büyük oranda denizel tortulanma ve birikme dönemidir. Bu dönemde <b>Tetis Okyanusu</b> oluşmuştur ve gelecekte gerçekleşecek olan Alp-Himalaya orojenezinin hazırlık aşaması yaşanmıştır.",
    "⛰️ <b>3. JEOLOJİK ZAMAN (TERSİYER):</b> Türkiye'nin ana hatlarının oluştuğu çok hareketli bir dönemdir.<br>• <b>Alp-Himalaya kıvrımı</b> gerçekleşmiştir.<br>• Bu kıvrılma sonucunda <b>Toroslar</b> ve <b>Kuzey Anadolu Dağları</b> oluşmuştur.<br>• Ülkemizdeki <b>ana fay kuşakları</b> ve Ege'nin <b>horst-graben sistemi</b> bu dönemde kırılmalarla meydana gelmiştir.<br>• Karadeniz ve Akdeniz ilk olarak göl şeklinde oluşmuştur.<br>• Türkiye için çok önemli olan <b>tuz, bor, linyit, petrol ve doğalgaz</b> yatakları bu zamanda oluşmuştur.<br>• Türkiye'deki volkanik dağların büyük kısmı bu dönemde faaliyet göstermiştir.",
    "🧊 <b>4. JEOLOJİK ZAMAN (KUVATERNER):</b> Yakın dönemi ve bugünkü görünümü kapsar.<br>• <b>Egeit karası çökmüş</b>, yerine <b>Ege Denizi</b> oluşmuştur.<br>• Eski birer akarsu vadisi olan alanların çökmesiyle <b>İstanbul ve Çanakkale Boğazları</b> ile <b>Marmara Denizi</b> açılmıştır.<br>• Karadeniz ve Akdeniz tam bir deniz özelliği kazanmıştır.<br>• <b>Anadolu Yarımadası toptan yükselmiştir.</b><br>• Anadolu bu dönemde 4 kez buzul çağı (buzullaşma) yaşamıştır.",
    "🌱 <b>NOT - TÜRKİYE'NİN GENÇ OLUŞUMU:</b> Türkiye jeolojik olarak genç oluşumlu (çoğunlukla 3. ve 4. zamanda şekillenmiş) bir ülkedir. <b>Bu nedenle;</b> ortalama yükseltisi fazladır, sık sık tektonik depremler yaşanır, sıcak su kaynakları (jeotermal/fay) yaygındır, tektonik oluşumlu ova ve göller fazladır, <b>linyit rezervi oldukça zengindir.</b>",
    "🪵 <b>KÖMÜR REZERVİ İPUCU:</b> Ülkemizde <b>Linyit kömürünün</b> çok yaygın olması Türkiye arazisinin <b>genç oluşumlu</b> olduğunu kanıtlar. Eğer ülkemizde <b>Taş kömürü</b> (Zonguldak çevresi) çok fazla olsaydı, bu arazinin 1. Jeolojik Zaman'dan kalan <b>yaşlı/eski bir arazi</b> olduğunu kanıtlayacaktı.",
    "🏔️ <b>C. DAĞLAR (Oluşumuna Göre Kıvrım Dağlar):</b> Esnek tabakaların sıkışarak kıvrılmasıyla oluşan dağlarımızdır.<br>• <b>Yıldız-İstıranca Dağları:</b> Trakya / Kırklareli<br>• <b>Küre Dağları:</b> Kastamonu-Sinop hattı<br>• <b>Ilgaz Dağları:</b> Kastamonu-Çankırı hattı<br>• <b>Köroğlu Dağları:</b> Bolu çevresi<br>• <b>Canik Dağları:</b> Samsun (Yükseltisi azdır)<br>• <b>Kaçkarlar:</b> Rize-Artvin hattı (En yüksek kıvrım hattı)<br>• <b>Sultan Dağları:</b> Afyon-Konya-Isparta arası<br>• <b>Geyik Dağları:</b> Akdeniz Bölgesi<br>• <b>Bey Dağları:</b> Antalya çevresi<br>• <b>Aladağlar:</b> Akdeniz-Niğde-Adana-Kayseri hattı<br>• <b>Cilo Dağları:</b> Hakkari (Buzul dağları)<br>• <b>Mercan (Munzur) Dağları:</b> Tunceli-Erzincan hattı",
    "🪓 <b>C. DAĞLAR (Oluşumuna Göre Kırık Dağlar):</b> Sert tabakaların kırılmasıyla (Horst-Graben) oluşan dağlardır. En yaygın olduğu yer Ege Bölgesi'dir (Batı Anadolu).<br>• <b>KUZEYDEN GÜNEYE EGE DAĞLARI KODLAMASI:</b> <b>KAZ</b> (Kaz Dağı) - <b>MA</b> (Madra Dağı) - <b>YUNT</b> (Yunt Dağı) - <b>BOZ</b> (Bozdağlar) - <b>AYI</b> (Aydın Dağları) - <b>ME</b>ledi (Menteşe Dağları).<br>• <b>⚠️ AKDENİZ İSTİSNASI:</b> Hatay'da bulunan <b>Amanos (Nur) Dağları</b> Akdeniz Bölgesi'nde olmasına rağmen bir kırık dağdır (Horst). Önündeki <b>Amik Ovası</b> ise grabendir.",
    "🌋 <b>C. DAĞLAR (Oluşumuna Göre Volkanik Dağlar):</b> Magmanın yüzeye çıkıp soğumasıyla oluşan konilerdir.<br>• <b>Kula Volkanları (Manisa - Ege):</b> Türkiye'nin en genç oluşumlu volkanik sahasıdır.<br>• <b>Mardin - Karacadağ:</b> Güneydoğu Anadolu'da yer alır. Lavları çok akıcı olduğu için yükselmek yerine çevreye yayılmıştır, Türkiye'nin <b>en yayvan volkan konisidir (Kalkan Volkan).</b><br>• <b>💡 İÇ ANADOLU VOLKANLARI KODLAMASI (Ke-Ke-M-E-Hasan):</b> <b>Ke</b>-Karacadağ (Konya), <b>Ke</b>-Karadağ (Karaman), <b>M</b>-Melendiz (Niğde), <b>E</b>-Erciyes (Kayseri) ve <b>Hasan</b> Dağı (Aksaray-Niğde).<br>• <b>💡 DOĞU ANADOLU VOLKANLARI KODLAMASI (NE-S-T-A):</b> <b>Ne</b>-Nemrut (Bitlis), <b>S</b>-Süphan (Bitlis-Van), <b>T</b>-Tendürek (Ağrı-Van), <b>A</b>-Ağrı Dağı (Ağrı-Iğdır).",
    "🌊 <b>DAĞLARIN KIYIYA PARALEL UZANDIĞI YERLERİN ÖZELLİKLERİ (Karadeniz ve Akdeniz):</b><br>• Kıyı ile iç kesimler arasında iklim, nem ve bitki örtüsü farkı fazladır.<br>• Kıyı ile iç kesimler arasında ulaşım zor, geçitlerle sağlanır ve yol yapım maliyeti yüksektir.<br>• Kıyı çizgisi oldukça sadedir; koy, körfez, doğal liman ve ada sayısı azdır.<br>• Deniz aniden derinleşir, yani <b>kıta sahanlığı dardır (Şelf alanı dardır).</b><br>• Deniz derin olduğu için kıyıda malzeme birikemez; <b>Delta oluşumu zor, falez (yalıyar) oluşumu çok kolaydır.</b><br>• Kıyı tipi olarak <b>Boyuna Kıyı Tipi</b> görülür.<br>• Dağlar nemli hava kütlesini karşıladığı için kıyıların yağış miktarı fazladır.<br>• Kıyının kuş uçumu uzunluğu ile gerçek uzunluğu arasındaki fark azdır.",
    "🗂️ <b>GENEL DAĞ SINIFLANDIRMASI (ÖZET KUŞAKLAR):</b><br>• <b>Toroslar Kuşağı:</b> Batıda Muğla'dan başlayıp Van Gölü'nün güneyine kadar uzanan güneydeki kıvrım dağların genel adıdır.<br>• <b>Kuzey Anadolu Dağları:</b> Türkiye'nin kuzeyinde, Karadeniz boyunca uzanan kuzey kıvrım sistemidir.<br>• <b>Batı Anadolu Dağları:</b> Ege'deki kırıklı sistemdir (Kaz, Madra, Yunt, Bozdağlar, Aydın, Menteşe).<br>• <b>Orta ve Doğu Anadolu Volkanik Grubu:</b> İç Anadolu ve Doğu Anadolu'daki tektonik hatlar üzerine dizilmiş volkan konileridir."
];