// notlar/cografya-5-not.js
window.cografya_5_notlari = [
    "🌾 <b>TÜRKİYE'NİN OVALARI:</b> Çevresine göre alçakta kalan, akarsular tarafından taşınan alüvyonlarla kaplı ya da tektonik/karstik süreçlerle oluşmuş düzlüklere ova denir. Oluşumlarına göre karstik, delta, tektonik, volkanik, dağ eteği ve dağ içi ovaları olarak sınıflandırılır.",
    "🧪 <b>1. KARSTİK OVALAR (GÖLOVALAR):</b> Batı Toroslar kuşağında (Akdeniz ve Güney Ege), kalker, jips ve dolomit gibi kolay eriyebilen kayaçların bulunduğu alanlarda oluşan ovalardır. Bu ovaların tabanı verimsiz karstik malzemeyle kaplıdır.",
    "💡 <b>KARSTİK OVALAR KODLAMASI (TAKKEM):</b><br>• <b>T</b>efenni (Burdur)<br>• <b>A</b>cıpayam (Denizli)<br>• <b>K</b>orkuteli (Antalya)<br>• <b>K</b>estel (Burdur)<br>• <b>E</b>lmalı (Antalya)<br>• <b>M</b>uğla ovası.",
    "🌊 <b>2. DELTA OVALARI:</b> Akarsuların iç kesimlerden taşıdığı alüvyonları, gelgit akıntısının az ve kıta sahanlığının geniş olduğu deniz kıyılarında biriktirmesiyle oluşan toprağı son derece verimli ovalardır.",
    "🗺️ <b>TÜRKİYE'DEKİ BAŞLICA AKARSU VE DELTA OVALARI EŞLEŞTİRMESİ:</b><br>• <b>Kızılırmak</b> → <b>Bafra Ovası</b> (Orta Karadeniz)<br>• <b>Yeşilırmak</b> → <b>Çarşamba Ovası</b> (Orta Karadeniz)<br>• <b>Seyhan ve Ceyhan nehirleri</b> → <b>Çukurova</b> (Akdeniz - Türkiye'nin en büyük delta ovası)<br>• <b>Göksu Nehri</b> → <b>Silifke Ovası</b> (Akdeniz)<br>• <b>Bakırçay</b> → <b>Dikili Ovası</b> (Ege)<br>• <b>Gediz</b> → <b>Menemen Ovası</b> (Ege)<br>• <b>Küçük Menderes</b> → <b>Selçuk Ovası</b> (Kuşadası/Ege)<br>• <b>Büyük Menderes</b> → <b>Balat Ovası</b> (Aydın/Ege)",
    "💥 <b>3. TEKTONİK OVALAR:</b> Yer kabuğu hareketleri (faylanmalar) sonucu çöken alanların akarsu alüvyonlarıyla dolması sonucu oluşur. Türkiye genç oluşumlu olduğu ve kırık hatları çok fazla bulunduğu için en yaygın ova türüdür.",
    "🗺️ <b>FAY HATLARI ÜZERİNDEKİ TEKTONİK OVALAR:</b><br>• <b>Kuzey Anadolu Fay Hattı (KAF) Ovaları:</b> Tercan, Erzincan, Niksar, Erbaa, Merzifon, Suluova.<br>• <b>Doğu Anadolu Fay Hattı (DAF) Ovaları:</b> Elazığ, Malatya, Muş, Amik (Hatay), Maraş, Bingöl.<br>• <b>Batı Anadolu Fay Hattı (BAF) Ovaları:</b> Ege'deki graben çöküntülerinde yer alan Salihli, Turgutlu, Ataşehir ovaları.",
    "🏗️ <b>DİĞER ÖZEL OLUŞUMLU OVALAR:</b><br>• <b>Dağ Eteği Ovası:</b> Dağlık kütlelerin yamaçlarından inen malzemelerin etekte birleşmesiyle oluşur; en güzel örneği <b>Bursa Ovası</b>'dır.<br>• <b>Dağ İçi Ovası:</b> Dört bir tarafı dağlarla çevrili iç havzalarda oluşur; Doğu Anadolu'daki <b>Muş Ovası</b> buna örnektir.<br>• <b>Volkanik Ova:</b> Volkanik malzemelerin ve tüflerin düzlüklerde birikmesiyle oluşur; Kayseri'deki <b>Develi Ovası</b> en net örneğidir.",
    "👑 <b>NOTLAR - EN BÜYÜKLER:</b><br>• Türkiye'nin kıyıda yer alan <b>en büyük delta ovası Çukurova</b>'dır.<br>• Türkiye'nin <b>en büyük iç ovası</b>, aynı zamanda tektonik bir çöküntü alanı olan <b>Konya Ovası</b>'dır."
];