// notlar/cografya-2-not.js
window.cografya_2_notlari = [
    "🌍 <b>İÇ KUVVETLER:</b> Yer şekillerinin oluşumunda enerjisini yerin derinliklerinden (magmadan) alan kuvvetlerdir. Orojenez, Epirojenez, Volkanizma ve Depremler (Seizma) olmak üzere dört ana grupta incelenir.",
    "🏔️ <b>a. OROJENEZ:</b> Dağ oluşumu anlamına gelir. Türkiye'deki kırık dağlar ve kıvrım dağların oluşmasında orojenez etkili olmuştur.",
    "💥 <b>KIRIK SİSTEM (OROJENEZ):</b> Kırılma sonucunda yüksekte kalan yerlere <b>horst</b>, çöküntü alanlara <b>graben (depresyon)</b> adı verilir. Kırık dağlar ülkemizde en yaygın olarak Batı Anadolu'da (Ege Bölgesi) görülür.",
    "〰️ <b>KIVRIM SİSTEM (OROJENEZ):</b> Kıvrılma sonucunda oluşan kubbe yapılara <b>antiklinal</b>, çöküntü alanlarına ise <b>senklinal</b> denir. Kıvrım dağlar Türkiye'de Toroslar ve Kuzey Anadolu Dağları'nda yaygındır.<br>• <b>Not:</b> Türkiye'nin kıvrım dağları Alp-Himalaya sistemine bağlıdır.",
    "⚖️ <b>b. EPİROJENEZ:</b> Kıta oluşumu demektir. Karasal yer kabuğu ile okyanusal yer kabuğu arasında <b>izostatik</b> denilen bir ağırlık dengesi vardır. Karalarda tortulanma veya buzullaşma sonucu yük artışı yaşandığında karalar çöker.",
    "📉 <b>TÜRKİYE'DE EPİROJENEZİN SONUÇLARI:</b><br>• Anadolu Yarımadası genel olarak yükselir.<br>• Karadeniz ve Akdeniz (deniz alanları) alçalmaktadır.<br>• Çukurova ve Trakya (Ergene Havzası) çökmektedir.<br>• Doğu Anadolu Bölgesi yükselmektedir.<br>• İstanbul Boğazı ve Çanakkale Boğazları, epirojenez ile yaşanan çökme sonucunda eski nehir vadilerinin deniz suları altında kalmasıyla açılmıştır.",
    "🌋 <b>c. VOLKANİZMA:</b> Magmanın yer kabuğunun zayıf noktalarından yeryüzüne doğru hareket etmesidir. Yüzey ve derinlik volkanizması olarak ikiye ayrılır.",
    "💎 <b>DERİNLİK VOLKANİZMASI:</b> Magmanın yüzeye çıkamadan yer altında soğumasıdır. Bursa Uludağ <b>batolit</b> (iç püskürük granit kaya) yapısına en güzel örnektir.",
    "🔥 <b>YÜZEY VOLKANİZMASI:</b> Magmanın yeryüzünde katılaşmasıyla volkanik koniler oluşur. Basınçla havaya uçması sonucu <b>krater</b> oluşur. Krater büyüdüğünde <b>kaldera</b> olur, içinin su dolmasıyla krater gölü olur (Ör: Nemrut Krater Gölü).<br>• <b>Maar:</b> Gaz sıkışması sonucu yaşanan patlama çukurlarıdır; Konya Meke Maar'ı en önemli örnektir.",
    "🗺️ <b>TÜRKİYE'NİN VOLKANİK ARAZİLERİ (1. BATI ANADOLU - MARMARA & EGE):</b><br>• <b>Biga Yarımadası Çevresi (Çanakkale):</b> BİGA = BIG (Büyük): Çanakkale Boğazı'nın yanındaki o devasa çıkıntıyı 'Büyük (Big) Volkanik Arazi' olarak kodlayın.<br>• <b>Kaz Dağı Çevresi (Balıkesir/Çanakkale sınırları):</b> KAZ → KÖZ: 'Kaz Dağları'nın altı aslında bir KÖZ (volkan)' diye düşünün. Kazlar yeşilliği sever ama altı volkanik arazidir.<br>• <b>Uludağ Çevresi (Bursa):</b> İçte kalan volkan (Batolit): Uludağ dışarı püskürememiş, içeride katılaşmış bir derinlik volkanizmasıdır. ULU dağ, volkanik ateşini dışarı fırlatmak yerine ULUCA kendi içinde saklamış!<br>• <b>Afyon Çevresi:</b> Bölgedeki geçiş kuşağı volkanik arazilerindendir.",
    "🗺️ <b>TÜRKİYE'NİN VOLKANİK ARAZİLERİ (2. İÇ ANADOLU VE GEÇİŞ KUŞAKLARI):</b><br>• <b>Köroğlu Dağları Çevresi (Bolu/Çankırı):</b> Köroğlu'nun Öfkesi: Bolu Beyi'ne isyan eden Köroğlu'nun içindeki intikam ateşi, bu dağların volkanik geçmişinden gelir! Karadeniz'in arkasındaki o geniş kahverengi alan Köroğlu'nun tüfeğinin patladığı yerdir.<br>• <b>Göller Yöresi Doğusu (Isparta/Burdur):</b> Gölün Dibindeki Volkan: Isparta'daki meşhur Gölcük Krater Gölü buradadır. 'Güller diyarı Isparta'da güller, mineral zengini volkanik toprakta açar' diye kodlayabilirsiniz.<br>• <b>Karacadağ – Karadağ Çevresi (Konya/Karaman):</b> İki Kara Yan Yana: İç Anadolu'nun güneyinde yan yana duran iki siyah leke düşünün.<br>• <b>Hasan Dağı Çevresi (Aksaray/Niğde):</b> Kapadokya tüflerini de oluşturan volkanik hat.<br>• <b>Erciyes Dağı (Kayseri):</b> Bölgenin en yüksek ve meşhur stratovolkan konisidir.",
    "🗺️ <b>TÜRKİYE'NİN VOLKANİK ARAZİLERİ (3. GÜNEY VE DOĞU ANADOLU):</b><br>• <b>Hatay – Hassa Çevresi:</b> HASSA = HASSAS / LAV TÜPÜ: Türkiye'nin ilk lav tüpü mağaralarının bulunduğu bazaltik arazi.<br>• <b>Mardin – Karacadağ (Şanlıurfa/Diyarbakır sınırı):</b> Çok akıcı lavlar yaydığı için kalkan biçimli bir volkandır.<br>• <b>Van Gölü Batısı (Nemrut, Süphan, Tendürek, Ağrı):</b> NE-S-T-A Hattı: Van Gölü'nün batısından Ermenistan sınırına doğru bir çizgi gibi dizilirler: Nemrut, Süphan, Tendürek, Ağrı dağları.<br>• <b>Erzurum – Kars Çevresi:</b> Kara Toprak (Çernezyom): Bölgedeki dünyanın en verimli kara toprakları, buradaki devasa volkanik lav platolarının zamanla çözünmesiyle oluşmuştur.",
    "🍇🥔 <b>VOLKANİK ARAZİLERDE TARIM:</b> Bu alanlarda oluşan volkanik topraklar mineral yönünden çok zengin olduğundan özellikle <b>üzüm yetiştiriciliği (bağcılık)</b> ve <b>patates</b> üretimi için oldukça uygundur.",
    "🚨 <b>DEPREMLER (SİEZMA):</b> Anadolu'nun komşu levhalar ve kıtalar tarafından sıkıştırılması sonucunda üç büyük fay zonu oluşmuştur:<br>• <b>Kuzey Anadolu Fayı (KAF):</b> Bingöl Karlıova'dan başlar, Kuzey Anadolu Dağları'nın güneyini izleyerek Saros Körfezi'nden batıya gider.<br>• <b>Doğu Anadolu Fayı (DAF):</b> Bingöl Karlıova'dan başlar; Elazığ, Malatya, Maraş hattını takip ederek Hatay'dan güneye gider.<br>• <b>Batı Anadolu Fayı (BAF):</b> Ege Bölgesi'ndeki horst-graben sistemine bağlı olarak gelişen çok parçalı kırık sistemidir."
];