// notlar/cografya-1-not.js
window.cografya_1_notlari = [
    "🗺️ <b>BÖLGELERİN GENEL KARAKTERİ:</b><br>• Ters bir olay varsa (Bakı tersliği vb.) <b>Karadeniz Bölgesi</b>'ndedir.<br>• <b>Marmara Bölgesi:</b> Alçaktır, kalabalıktır.<br>• <b>Ege Bölgesi:</b> Kırıklı fay hatları yaygındır, geniş ovalar vardır.<br>• <b>Akdeniz Bölgesi:</b> Karstik yapı yaygındır.<br>• <b>Güneydoğu Anadolu:</b> Düz ve kuraktır.<br>• <b>Doğu Anadolu:</b> Yüksek ve volkaniktir.<br>• <b>İç Anadolu:</b> Düzdür, etrafı dağlıktır.",
    "📐 <b>TÜRKIYE'NİN MUTLAK KONUMU:</b> Türkiye, <b>36° - 42° Kuzey enlemleri</b> ile 26° - 45° Doğu boylamları arasındadır. Kuzey Yarım Küre'de ve Yengeç Dönencesi'nin kuzeyinde yer alır.",
    "🌍 <b>ORTA ILIMAN KUŞAK ÖZELLİKLERİ (A-B-C-D):</b><br>• <b>A</b>kdeniz iklimi görülür.<br>• <b>B</b>atı rüzgarları görülür.<br>• <b>C</b>ephe yağışları görülür (Ekvatoral sıcak hava ile kutup soğuk havasının karşılaşması).<br>• <b>D</b>ört mevsim belirgindir.",
    "☀️ <b>YENGEÇ DÖNENCESİ'NİN KUZEYİNDE OLMANIN SONUÇLARI:</b> Güneş ışınları hiçbir zaman <b>90° açıyla gelmez</b>. Öğle vakti gölge boyu <b>hiçbir zaman sıfır olmaz</b>. Dağların <b>güney yamaçları (Bakı)</b> güneş ışınlarını daha büyük açıyla alır. Buna bağlı olarak güney yamaçlarda sıcaklık yüksektir, karlar erken erir, sel/taşkın riski artar, otlaklar erken açılır, koyun otlatma mevsimi ve bitki olgunlaşması erken başlar.",
    "❗ <b>BAKI TERSLİĞİ İSTİSNASI:</b> Karadeniz Dağları'nın kış aylarında <u>kuzey yamaçlarının</u> güney yamaçlarından daha sıcak/ılık olması bakı ile çelişir. Bu durum <b>denizellik ve nemlilik</b> ile açıklanır.",
    "🥶 <b>KUZEY YARIM KÜRE'DE OLMANIN SONUÇLARI:</b> Güneyden kuzeye gidildikçe güneş ışınlarının geliş açısı, sıcaklık, buharlaşma ve denizlerin tuzluluk oranı <b>azalır</b>. Tarım ürünlerinin olgunlaşma ve karın yerde kalma süresi <b>uzar</b>. <b>Çizgisel hız azalır</b>, grup ve tan (doğuş/batış) süreleri uzar. Güneyden esen rüzgarlar sıcaklığı artırırken, kuzeyden esenler düşürür.",
    "📍 <b>AYNI ENLEM ÜZERİNDEKİ MERKEZLER:</b> Yıl boyunca güneş ışınlarının geliş açısı, çizgisel hız, gece-gündüz süre farkı ve öğle vakti gölge boyları <b>kesinlikle aynıdır</b>. (Örn: İzmir ve Van). Sıcaklıkları farklıysa sebebi özel konumdur.",
    "⏳ <b>AYNI BOYLAM ÜZERİNDEKİ MERKEZLER:</b> (Örn: İzmit - Bilecik - Afyon - Finike)<br>• <b>Yerel saatleri</b> aynıdır.<br>• <b>Öğle vakitleri</b> aynıdır.<br>• Gün içinde gölge boyunun <b>en kısa olduğu an</b> aynıdır.<br>• <i>Dikkat:</i> Başlangıç meridyenine olan kuş uçuşu uzaklıkları ve gece-gündüz süreleri <u>farklıdır</u> (Kutba doğru meridyenler daralır).",
    "💡 <b>ALTIN NOT (SÜRE KAVRAMI):</b> Bir soruda süre varsa; <b>Gündüz süresi</b> veya <b>Alacakaranlık (tan/grup) süresi</b> geçiyorsa bu durum doğrudan <b>ENLEM (Matematik Konum)</b> ile ilgilidir. Kuzey-güney kıyaslamaları enlemdir.",
    "⏰ <b>YEREL SAAT HESAPLAMA MANTIĞI:</b> Ardışık iki boylam arası zaman farkı <b>4 dakikadır</b>. Doğuda yerel saat her zaman daha ileri, batıda ise geridir. İki merkez arasındaki boylam farkı bulunup 4 ile çarpılarak zaman farkı hesaplanır.",
    "⛰️ <b>ÖZEL (GÖRECELİ) KONUM ELEMANLARI:</b><br>• <b>Yer Şekilleri:</b> Kısa mesafede değişir. Buna bağlı iklim, bitki örtüsü ve tarım da kısa mesafede çeşitlenir.<br>• <b>Yükselti:</b> Batıdan doğuya artar. Sıcaklık azalır, karın yerde kalma süresi ve kar yağışı artar, tarımsal olgunlaşma uzar, hidroelektrik potansiyeli artar.<br>• <b>Karasallık (Nem Azlığı):</b> Erken ve aşırı ısınır, erken ve aşırı soğur. Sıcaklık farkı fazladır (Örn: Şanlıurfa).<br>• <b>Denizellik (Nemlilik):</b> Geç ısınır, geç soğur. Aşırı ısınma/soğuma olmaz. Sıcaklık farkı azdır (Örn: Sinop).",
    "🚨 <b>ENLEM İLE AÇIKLANAMAYAN (ÇELİŞEN) ÖZEL KONUM ÖRNEKLERİ:</b><br>• Toroslar'da kısa mesafede iklimin değişmesi $\rightarrow$ <i>Yer şekilleri</i><br>• Aynı enlemdeki İzmir'in Van'dan sıcak olması $\rightarrow$ <i>Yükselti</i><br>• Kışın kuzeydeki Sinop'un güneydeki Yozgat'tan sıcak olması $\rightarrow$ <i>Denizellik</i><br>• Yazın Şanlıurfa'nın aynı enlemdeki Antalya'dan sıcak olması $\rightarrow$ <i>Karasallık</i><br>• Ege'de sık deprem olması $\rightarrow$ <i>Tektonik Yapı</i><br>• 💎 Türkiye'de <b>maden çeşitliliği fazladır ancak genel olarak rezervleri azdır.</b>",
    "📅 <b>DÖRT KRİTİK TARİH VE TÜRKİYE:</b><br>• <b>21 Mart / 23 Eylül (Ekinoks):</b> Gece-gündüz eşittir (12 saat). 21 Mart'tan sonra gündüzler geceleri geçerek uzamaya başlar.<br>• <b>21 Haziran (Yaz Solstisi):</b> Yaz başlar. En uzun gündüz, en kısa gölge yaşanır. Bu tarihten sonra gündüzler kısalmaya başlar.<br>• <b>21 Aralık (Kış Solstisi):</b> Kış başlar. En uzun gece, en uzun gölge yaşanır. Kuzeye gidildikçe gece süresi uzar (Örn: En uzun gece Sinop'ta). Bu tarihten sonra gündüzler uzamaya başlar ama 21 Mart'a kadar hala gecelerden kısadır.",
    "☀️ <b>MEVSİMSEL GÜNDÜZ DEĞİŞİMLERİ:</b><br>• <b>Yaz Döneminde (21 Mart - 23 Eylül):</b> Güneyden kuzeye doğru gidildikçe gündüz süresi uzar.<br>• <b>Kış Döneminde (23 Eylül - 21 Mart):</b> Kuzeyden güneye doğru gidildikçe gündüz süresi uzar."
];