// notlar/cografya-13-not.js
window.cografya_13_notlari  = [
    "💧 <b>TÜRKİYE'NİN AKARSULARI - GENEL ÖZELLİKLERİ:</b><br>• <b>Kaynakları:</b> Yüksek dağlık sahalardır.<br>• <b>Akış hızı, aşındırma gücü, hidroelektrik potansiyeli:</b> Fazladır (Sebebi: yükselti)<br>• <b>Denge profili:</b> Duzak yapısından uzaktır (Sebebi: yükselti)<br>• <b>Debileri (su miktarı):</b> Azdır (Sebebi: kurak iklim)<br>• <b>Rejimleri:</b> Düzensizdir<br>• <b>Ulaşım ve taşımacılığa uygunluk:</b> Uygun değildir<br>• <b>Boyları:</b> Kısadır (Sebebi: iklim, yer şekilleri, yarımada coğrafyası)",
    
    "🌊 <b>KAPALI HAVZALAR (Denize ulaşamayan akarsuların havzası):</b><br>• <b>Hazer Denizi'ne dökülen akarsuları:</b> Aras ve Kura nehirleri<br>• <b>Van Gölü Havzası</b><br>• <b>Tuz Gölü Havzası</b><br>• <b>Göller Yöresi Havzası</b><br>• <b>Konya Ovası Havzası:</b> Beyşehir, Tuz göllerini içerir<br>• <b>Afyon-Akarçay Havzası</b><br>⭐ <b>NOT: Tuz Gölü, Beyşehir Gölü, Konya Ovası → İç Anadolu Kapalı Havzası'nın küçük havzalarıdır.</b>",
    
    "🔵 <b>AÇIK HAVZALAR (Denize kavuşan akarsuların havzası):</b><br>Türkiye akarsuları <b>5 açik havzaya</b> dökülmektedir:<br>1. <b>Karadeniz Havzası</b> (En büyük açık havza)<br>2. <b>Marmara Havzası</b><br>3. <b>Ege Havzası</b><br>4. <b>Akdeniz Havzası</b><br>5. <b>Basra Körfezi Havzası</b>",
    
    "🏔️ <b>KARADENİZ HAVZASINA DÖKÜLEN AKARSULARI:</b><br>• <b>Çoruh:</b> Akış hızı çok fazladır. Yusufeli Barajı (En yüksek setli baraj) üzerinde bulunur.<br>• <b>Yeşilırmak:</b> Gümüşhane yakınlarından kaynağını alır. Kelkit Çayı ana kolu. Batıya hareket eder. Samsun'da Çarşamba Deltası oluşturur.<br>• <b>Kızılırmak:</b> Sivas Kızıldağ'dan kaynağını alır.<br>• <b>Bartın Çayı:</b> Küre Dağları'ndan kaynağını alır.<br>• <b>Filyos:</b> Köroğlu Dağları'ndan kaynağını alır.<br>• <b>Sakarya:</b> En çok coğrafi bölgede akış gösteren akarsudur.",
    
    "⚪ <b>MARMARA HAVZASINA DÖKÜLEN AKARSULARI:</b><br>• <b>Susurluk:</b> Kütahya yakınlarından kaynağını alır.",
    
    "🟡 <b>EGE HAVZASINA DÖKÜLEN AKARSULARI:</b><br>• <b>Meriç:</b> Bulgaristan'dan kaynağını alır.<br>• <b>Bakırçay</b><br>• <b>Gediz</b><br>• <b>Küçük Menderes</b><br>• <b>Büyük Menderes</b>",
    
    "🔴 <b>AKDENİZ HAVZASINA DÖKÜLEN AKARSULARI:</b><br>• <b>Dalaman Çayı:</b> Muğla'da, Menteşe Dağları'ndan kaynağını alır.<br>• <b>Aksu:</b> Göller Yöresi'nden kaynağını alır. Antalya'dan denize dökülür.<br>• <b>Köprüçay</b><br>• <b>Manavgat</b><br>• <b>Göksu</b><br>• <b>Ceyhan</b><br>• <b>Seyhan</b><br>• <b>Asi:</b> Lübnan'dan kaynağını alır.",
    
    "🛢️ <b>BASRA KÖRFEZİ HAVZASINA DÖKÜLEN AKARSULARI:</b><br>• <b>Fırat Nehri:</b> Türkiye'nin en büyük hidroelektrik barajları bu nehir üzerinde kurulmuştur (Atatürk, Karakaya, Keban, Birecik). Karasu ve Murat kolları birleşerek Fırat Nehri'ni oluşturur. Irak'ta Dicle ile birleşir, Şattülarap'a dönüşür.<br>• <b>Dicle Nehri:</b> Çıkışı Elazığ'daki Hazar Gölü'dür. Irak'ta Fırat ile birleşir.<br>• <b>Zap Suyu:</b> Fırat ve Dicle arasında Mezopotamya bölgesini oluşturur.<br>⭐ <b>NOT: Kaynağı Türkiye'de olup Irak'a (Basra Körfezi'ne) giden → Fırat, Dicle, Zap</b><br>⭐ <b>NOT: Aras ve Kura → Azerbaycan'a dökülen akarsurlardır.</b><br>⭐ <b>NOT: Çoruh → Gürcistan Batum'dan Karadeniz'e dökülür.</b>",
    
    "⚠️ <b>YURT DIŞINDA DOĞUP TÜRKİYE'DE DENİZE DÖKÜLEN AKARSULARI:</b><br>• <b>Meriç:</b> Bulgaristan'dan kaynağını alır → Taşkın yapar<br>• <b>Asi:</b> Lübnan'dan kaynağını alır, Suriye'den gelir → Taşkın yapar<br>⭐ <b>NOT: Bu konudan gelen sorular → Kaynakların yurt içi/yurt dışı olması ve ağız kesimlerinin konumunu sorar.</b>",
    
    "🌳 <b>TÜRKİYE'DEKİ GÖLLER - SINIFLANDIRILMASI:</b><br>1. <b>Karstik Göller:</b> Avlan, Kestel, Suğla, Elmalı, Salda (Kodlaması: AKSES)<br>2. <b>Volkanik Göller:</b> Nemrut Krater Gölü (Bitlis), Meke Gölü (Konya) - Dünyanın Nazar Boncuğu, Acıgöl (Nevşehir)<br>3. <b>Buzul Gölleri:</b> Kilimli Göl, Kara Göl, Aynalı Göl (Hepsi Uludağ'da)<br>4. <b>Tektonik Göller:</b> Tuz, Eğirdir, Manyas, Ulubat, İznik, Sapanca, Hazar, Eber, Seyfe, Akşehir, Aktaş<br>5. <b>Set Gölleri:</b><br>   ○ <b>Volkanik Set Gölleri (Doğu Anadolu):</b> Balık Gölü, Van Gölü, Çıldır Gölü, Haçlı Gölü, Nazik Gölü, Erçek Gölü<br>   ○ <b>Heyelan Set Gölleri (Karadeniz):</b> Yedigöller (Bolu), Abant (Bolu), Borabay (Amasya), Zinav (Tokat), Sera (Trabzon), Tortum (Erzurum)<br>   ○ <b>Alüvyal Set Gölleri:</b> Gala (Edirne), Eymir (Ankara), Mogan (Ankara), Marmara (Manisa), Bafa (Aydın), Köyceğiz (Muğla)<br>   ○ <b>Kıyı Set Gölleri:</b> Büyükçekmece, Küçükçekmece, Terkos (İstanbul), Balık Gölü (Bafra)<br>   ○ <b>Traverten Set Gölleri:</b> Otlukbeli Gölü (Erzincan) - Oluşum bakımından tek",
    
    "📊 <b>GÖLLER - GENEL ÖZELLİKLERİ:</b><br>• <b>Yıl içinde en çok alan değişen göl:</b> Tuz Gölü (Sebebi: sığ olması, buharlaşma)<br>• <b>Üzerinde ulaşım yapılan, demir yolu olan tek göl:</b> Van Gölü (Maliyeti azdır)<br>• <b>Gideğeni olan göller:</b> Tatlı suludur (Sulama suyu çıkan göller)<br>• <b>Gideğeni olmayan göller:</b> Tuzlu, sodalı, acı suludur<br>• <b>En büyük tatlı su gölü:</b> Beyşehir Gölü (Çarşamba Ovası)<br>• <b>En büyük 2. tatlı su gölü:</b> Kovada Gölü<br>• <b>Diğer tatlı su gölleri:</b> Manyas, Tortum, İznik, Sapanca, Hazar, Ulubat, Çıldır<br>• <b>Kerevit avlanan göller:</b> Beyşehir, Eğirdir<br>• <b>İnci kefali avlanan göl:</b> Van Gölü<br>• <b>Soda elde edilen göl:</b> Van Gölü<br>• <b>Tuz elde edilen göl:</b> Tuz Gölü<br>• <b>Turizm değeri olan göller:</b> Abant, Yedigöller, Uzungöl<br>• <b>Milli park olan göller:</b> Beyşehir, Manyas (Kuş Gölü)<br>• <b>Enerji üretilen göller:</b> Eğirdir, Hazar, Tortum, Çıldır<br>⭐ <b>NOT: Güneydoğu Anadolu'da doğal göl yoktur.</b>",
    
    "🏛️ <b>TÜRKİYE'NİN YER ALTI SULARI VE KAYNAKLARI:</b><br>• <b>Karstik (Voküz) Kaynak:</b> Silfonlu kaynak denir. Yağıştan beslenr, rejim düzensiz, sular soğuk ve kireçlidir.<br>• <b>Yamaç (Vadi) Kaynak:</b> Oldukça yaygındır. Yağıştan beslenr, sular soğuk, rejim düzensizdir.<br>• <b>Artezyen (Su Kuyusu):</b> İnsan eliyle yüzeye çıkar. Kurak yerde ihtiyaç fazladır. Yağıştan beslenr, sular soğuktur.<br>• <b>Fay Kaynağı:</b> Yer altında beslenr. Sular sıcaktır. İklimden etkilenmez. Jeotermal enerji üretir.",
    
    "💧 <b>TÜRKİYE'NİN TATLI SU PROJELERİ:</b><br>• <b>Barış Suyu (Can Suyu) Projesi (Kıbrıs):</b> 'Asrın Projesi' denmiştir. Geçitköy Barajı ile içme ve sulama suyu sağlanıyor.<br>• <b>Avşa Adası Deniz Suyu Projesi:</b> Balıkesir, Marmara Denizi sularını arıtıp içiyor.<br>• <b>Melen Çayı Projesi:</b> Düzce, Boğaziçi Tüneli ile Avrupa yakasına su verildi.<br>• <b>Kızılırmak Projesi:</b> Ankara, 2008-2014 yılları arasında temiz su ihtiyacı karşılandı.",
    
    "🌊 <b>TÜRKİYE'NİN DENİZLERİ:</b><br><b>A. KARADENİZ:</b><br>• <b>Tuzluluk oranı:</b> Az (Sebebi: enlem, bol yağış, bol akarsu)<br>• <b>Kıyı özelliği:</b> Boyuna kıyı (girinti çıkıntı az)<br>• <b>Balık çeşidi:</b> En az, Miktarı: En fazla<br>• <b>Nedenleri:</b> Sular serin, oksijenlı, planktonlu (besinli)<br><b>B. MARMARA DENİZİ:</b><br>• <b>Tuzluluk:</b> %22 civarında<br>• <b>Kıyı uzunluğu:</b> En kısa<br>• <b>Balık avlama:</b> Boğazlar önemli sahalar (Nedeni: akıntılar)<br>• <b>Akıntı sistemi:</b> Karadeniz'den Ege'ye üst akıntı (seviye farkı), Ege'den Karadeniz'e alt akıntı (yoğunluk farkı)<br>• <b>Körfezler:</b> İzmit, Gemlik, Bandırma, Erdek<br>• <b>Balık avlama sahaları:</b><br>   ○ İstanbul: Sarıyer, Beykoz<br>   ○ Çanakkale: Eceabat, Lapseki, Gelibolu<br><b>C. EGE DENİZİ:</b><br>• <b>Kıyı sığlığı:</b> En sığ kıyılar<br>• <b>Kültür balıkçılığı:</b> Gelişmiştir (Dalyan)<br>• <b>Kıta sahanlığı:</b> Geniştir<br>• <b>Coğrafi özellikler:</b> Koy, körfez, liman ve ada sayısı fazladır<br>• <b>Saros Körfezi:</b> En temiz körfez (kendi kendine temizlenme özelliği)<br><b>D. AKDENİZ:</b><br>• <b>Balık çeşidi:</b> En çok<br>• <b>Balık miktarı:</b> En az<br>• <b>Körfezler:</b> Antalya, İskenderun",
    
    "🌍 <b>TOPRAK VARLIĞI - ZONAl (YERLİ) TOPRAKLAR:</b><br><b>Oluşum Süreci:</b> Bulunduğu yörenin iklim ve ana kaya yapısı hakkında bilgi verir.<br><b>Fiziksel Çözülme:</b> Sıcaklık farkı fazla, karasal yerde yaygın, toprak oluşumu yavaş<br><b>Kimyasal Çözülme:</b> Sıcaklık farkı az, denizel yerde yaygın, toprak oluşumu hızlı",
    
    "🟤 <b>KAHVERENGI ORMAN TOPRAĞINI:</b><br>• <b>Bulunma alanı:</b> Karadeniz'de yaygındır<br>• <b>Humus:</b> Zengindir<br>• <b>Yıkanma:</b> Fazladır<br>• <b>Asitlik:</b> Asitçe zengindir<br>• <b>Alt türleri:</b><br>   ○ <b>Kireçli Orman (Yıkanma az):</b> İç kesimlerde yaygın<br>   ○ <b>Kireçsiz Orman (Yıkanma fazla):</b> Kıyı kesimlerinde yaygın",
    
    "⚫ <b>PODZOL TOPRAKLAR:</b><br>• <b>Bulunma alanı:</b> Karadeniz kestane yapraklı ormanları altında<br>• <b>Coğrafi dağılış:</b> Dağlık sahalarda, Doğu Karadeniz ve Zonguldak<br>• <b>İklim tipi:</b> Nemli soğuk bölge toprakları<br>• <b>Rengi:</b> Kül rengi",
    
    "⬛ <b>ÇERNOZEM TOPRAKLARI (Siyah Toprak):</b><br>• <b>Bulunma alanı:</b> Erzurum-Kars platolarında<br>• <b>Özellik:</b> Dünyanın en humuslu topraklarıdır<br>• <b>Tarımsal kullanım:</b> İşe yaramaz (İklim kötüdür)<br>• <b>Hayvancılık:</b> Büyükbaş hayvancılık yapılır",
    
    "🔴 <b>TERRA ROSSA (Kırmızı Akdeniz Toprağı):</b><br>• <b>Bulunma alanı:</b> Akdeniz'de yaygın<br>• <b>Rengi ve yapısı:</b> Kırmızı, demir oksitçe zengindir<br>• <b>Verimlilik:</b> Verimsiz (gübreleme ile verimli olur)<br>• <b>Tarım tipi:</b> Dikili tarıma (fidan, ağaç) uygundur (Elma, zeytin, muz, nar)",
    
    "🟡 <b>BOZKIR (STEP) TOPRAKLARI:</b><br>• <b>Oluşum nedeni:</b> Yağış azlığı<br>• <b>Verimlilik:</b> Sulama ile verimli olur<br>• <b>Alt türleri:</b><br>   ○ <b>Kahverengi Step:</b> Kireç ve tuz fazla, yıkanma az<br>   ○ <b>Kestane Rengi Step:</b> Yıkanma fazla, tuz ve kireç az",
    
    "💨 <b>INTRAZONAL TOPRAKLAR:</b><br>• <b>Hidromorfik:</b> Sulu toprak, göl/akarsu kenarında, drenaj gelişmemiştir<br>• <b>Halomorfik (Solonçak):</b> Tuzlu toprak, Tuz Gölü çevresi<br>• <b>Kalsimorfik (Rendzina / Vertisol):</b> Kalsiyum karbonatlı toprak, 'Taş doğuran toprak' (Ergene-Trakya)",
    
    "🪨 <b>AZONAL TOPRAKLAR:</b><br>• <b>Özellik:</b> Bulunduğu yörenin iklimi/ana kaya yapısı hakkında bilgi vermez. Belirgin katmanlaşma yoktur.<br><b>Alüvyal Topraklar:</b> Akarsu biriktirmesi, deltalar, oldukça verimli, kolay işlenir, yoğun tarım<br><b>Kolüvyal Topraklar:</b> Engebeli arazikte yamaçtan dökülerek çukur alanlarda biriken topraklar<br><b>Litosol Topraklar:</b> Engebeli araziette yamaçta kalan ince taneli, sığ taşlı topraklar<br><b>Regosol Toprak:</b> Kırıntılı topraklar, yumru köklü bitkilerin yetişmesine uygundur",
    
    "🌳 <b>TÜRKİYE'NİN BİTKİ VARLIĞI - GENEL BİLGİLER:</b><br>• <b>Bitki çeşidi:</b> Yaklaşık 12 bin çeşit bitki (Sebebi: iklim çeşitliliği)<br>• <b>En çok endemik tür bulunduğu yer:</b> Toroslar<br>• <b>En az endemik tür bulunduğu yer:</b> Trakya",
    
    "🌿 <b>ENDEMİK TÜR (Sadece bir yerdeki bitki):</b><br>• <b>İspir Meşesi:</b> Yozgat<br>• <b>Kazdağı Köknarı</b><br>• <b>Datça Hurması</b><br>• <b>Nemrut Soğanı</b><br>• <b>Anzer Çayı</b><br>• <b>Ters Lale</b><br>• <b>Kara Gül (Halfeti Gülü)</b><br>• <b>Sığla Ağacı (Günlük Ağacı):</b> Muğla Köyceğiz Gölü çevresi, yağ elde edilir, kozmetik sanayisinde kullanılır, koruma altındadır",
    
    "👑 <b>KLİMAKS TÜR (Bir iklimin baskın bitkisi):</b><br>• <b>Karadeniz:</b> Ladin<br>• <b>Akdeniz:</b> Kızılçam<br>• <b>Karasal:</b> Sarıçam (Kars-Sarıkamış)",
    
    "💀 <b>RELİKT TÜR (Kalıntı Tür):</b> Geçmiş jeolojik dönemlerden kalma bitkilerdir.",
    
    "🌲 <b>AĞAÇ TOPLULUĞU - GENEL BİLGİLER:</b><br>• <b>Türkiye'nin yüz ölçümünün %28'i:</b> Ormanlıktır<br>• <b>Türkiye'deki en çok arazi:</b> Ormanlıktır<br>• <b>En yaygın orman ağacı:</b> Meşe (Sebebi: iklimine uygundur)<br>• <b>Dünyada en çok kızılçam:</b> Türkiye'dedir<br>• <b>En saf ormanlar:</b> Fıstık çamı (İzmir-Kozak Yaylası)<br>• <b>En çok ormanı olan il:</b> Antalya",
    
    "📏 <b>YÜKSELTI SIRASIYLA ORMAN AĞAÇLARI (Yüksekten Aza):</b><br>Meşe → Kızılçam → Kayın → Ardıç → Sarıçam → Sedir → Ladin",
    
    "🌳 <b>ORMAN AĞAÇLARININ COĞRAFI DAĞILIŞI:</b><br>• <b>Meşe:</b> Türkiye'nin hemen her bölgesi, en yaygın ağaçlardan biri<br>• <b>Kızılçam:</b> Akdeniz ve Ege kıyıları, Güney Marmara<br>• <b>Kayın:</b> Karadeniz kıyıları, özellikle Doğu ve Batı Karadeniz<br>• <b>Ardıç:</b> İç Anadolu, Doğu Anadolu, Toroslar, kurak ve yüksek alanlar<br>• <b>Sarıçam:</b> Doğu Anadolu, Doğu Karadeniz'in yüksek kesimleri, İç Anadolu'nun kuzeyi, soğuk iklim<br>• <b>Sedir:</b> Dağ tepelerinde<br>• <b>Ladin:</b> Yüksek dağlık sahalarda",
    
    "🍂 <b>KARADENİZ ORMANLARI:</b><br>• <b>Özelliği:</b> Türkiye'nin en yoğun orman alanını oluşturur<br>• <b>0-1000 metre:</b> Geniş yapraklı ormanlar (kayın, kestane, gürgen, ıhlamur)<br>• <b>1000-1500 metre:</b> Karışık yapraklı ormanlar<br>• <b>1500-2000 metre:</b> İğne yapraklı ormanlar (sarıçam, karaçam, göknar, ladin)",
    
    "☀️ <b>AKDENİZ ORMANLARI:</b><br>• <b>0-500 metre:</b> Yaz kuraklığına dayanıklı meşe türleri ve kızılçamlar<br>• <b>500-1000 metre:</b> Meşe türleri ve kızılçamlar<br>• <b>1000-2100 metre:</b> İğne yapraklı türler (karaçam, ardıç, katran), sedir, fıstık çamı",
    
    "❄️ <b>KARASAL ORMANLAR (İç ve Doğu Anadolu):</b><br>• <b>En yüksek sınır:</b> 2800 metre (Doğu Anadolu)<br>• <b>Ormanlık kuşaklar:</b> Meşe, karaçam, sarıçam, ardıçtan oluşan orman kuşakları",
    
    "🌾 <b>ÇALI TOPLULUĞU:</b><br><b>Maki:</b> Kızılçam ormanlarının tahrip edilmesiyle ortaya çıkar (Zeytin, keçiboynuzu, zakkum, lavanta, kocayemiş, defne)<br>• <b>Tahrip sonrası:</b> 'Garig' oluşur<br><b>Psödomaki:</b> Kızılçam dışı orman tahribatı (Fındık)",
    
    "🌾 <b>OT TOPLULUĞU:</b><br><b>Bozkır:</b> İlkbaharda yeşerip, yaz sararıp, sonbahar kuruyan, kış ortadan kalkan otlar (Sığır kuyruğu, çoban yastığı, geven otu, üzerlik otu)<br>• <b>Antropojen Bozkır (Ağaçlı Bozkır):</b> İnsan eliyle orman tahribi sonucunda (Yozgat, Ankara)<br><b>Çayır:</b> Erzurum-Kars yaylalarında, yüksek dağ çayırlarına 'alpin çayır' denir",
    
    "🗺️ <b>TÜRKİYE'NİN FLORA (DOĞAL BİTKİ ÖRTÜSÜ) - 3 ANA FLORA BÖLGESI:</b><br><b>1. AVRUPA-SİBİRYA FLORA BÖLGESI:</b><br>• <b>Bulunma alanı:</b> Karadeniz kıyıları ve Marmara'nın kuzeyi<br>• <b>Özelliği:</b> Yağış fazla, ormanlar geniş yer kaplar<br>• <b>Bitkiler:</b> Kayın, gürgen, kestane, ladin, köknar<br><b>2. AKDENİZ FLORA BÖLGESI:</b><br>• <b>Bulunma alanı:</b> Akdeniz, Ege kıyıları ve Güney Marmara<br>• <b>İklimi:</b> Yazlar sıcak ve kurak, kışlar ılık ve yağışlı<br>• <b>Bitkiler:</b> Kızılçam, zeytin, defne, keçiboynuzu, maki<br><b>3. İRAN-TURAN FLORA BÖLGESI:</b><br>• <b>Bulunma alanı:</b> İç Anadolu, Doğu Anadolu, Güneydoğu Anadolu<br>• <b>İklimi:</b> Karasal ve kurak iklim hâkimdir<br>• <b>Bitkiler:</b> Bozkır bitkileri (geven, yavşan, kekik), ardıç"
];