// notlar/tarih-8-not.js
window.tarih_9_notlari = [
    "📖 <b>XIX. YÜZYIL OSMANLI DEVLETİ DAĞILMA DÖNEMİ - GENEL BAKIŞ:</b><br>18. yüzyılın sonunda başlayan reformlar, 19. yüzyılda Batı baskısı ve iç çöküntü karşısında yetersiz kalmıştır. Bu dönem, Osmanlı'nın toprak kaybı, uluslararası sorunların ortaya çıkışı ve modern Avrupa devlet sistemine dahil olma çabalarının dönemidir. Napolyon ile başlayan dönem, Balkan isyanları, azınlık meselelerinin uluslararası boyut kazanması ve nihayet Rusya'nın açık hedefleriyle sonlanır.",
    
    "🎭 <b>NAPOLYON DÖNEMINDEN TANZIMAT'A KADAR (1798-1839):</b><br>Bu dönem Osmanlı'nın baskı altında olduğu, her hamlesinin başka devletlerin müdahalesi ile karşı karşıya kaldığı, yeni bir dengeleme politikası aradığı dönemdir. Kısaca: Osmanlı'nın tehlikeli yalnızlığı ve Avrupa'nın dikkatli gözlerinin dönemi.",
    
    "⚡ <b>1798: NAPOLYON MISIR'I İŞGAL ETTİ - TÜRKİYE'NİN BAĞIMSIZLIĞINI YİTİRME BAŞLANGICI:</b><br>• <b>Olay:</b> Napolyon Mısır'ı işgal etti. Osmanlı topraklarında Avrupa askerinin ilk büyük tehdidi.<br>• <b>Osmanlı'nın Tepkisi:</b> Cezzar Ahmet Paşa Akka'da Napolyon'u durdurdu. ⭐ <b>Nizam-ı Cedid Ordusu'nun ilk ve son başarısı bu savunmadır.</b><br>• <b>Stratejik Anlam:</b> Osmanlı kendi başına Avrupa tehdidine karşı çıkabilse de, uzun süreli mücadele veremeyeceğini anlamıştır. Bu, Osmanlı'nın Avrupa devletlerine muhtaç olacağının ilk işaretidir.",
    
    "📜 <b>1801: EL ARİŞ ANTLAŞMASI - MÜTTEFIK ARAMA ÇABASI:</b><br>• <b>Antlaşma:</b> Fransızlar Mısır'dan geri çekildi.<br>• <b>Osmanlı Açısından Anlam:</b> İlk defa Osmanlı, Rusya ve İngiltere'den yardım istedi. Başında Cezzar Ahmet Paşa'nın uluslararası müttefik arayışı vardı. Böylece başı sonu gelmeyen dış bağımlılık başlamıştır.",
    
    "✅ <b>1802: PARİS PAKTI - ULUSLARARASI TANINIŞ:</b><br>• <b>Karar:</b> Mısır'ın Osmanlı Devleti'ne ait olduğu resmen kabul edildi.<br>• <b>Fakat Gerçek:</b> Mısır kontrolü Osmanlı'nın dışındadır. Sadece kâğıt üzerinde egemenlik vardır. Bu, 19. yüzyıl Osmanlı sorununun temelini oluşturur: <b>egemenlik var ama kontrol yok.</b>",
    
    "🔥 <b>1804: KARA YÖRGİ İSYANI - BALKAN SORUNLARININ BAŞLANGICI:</b><br>• <b>İsyancı:</b> Kara Yorgi (Karageorge) önderliğinde Sırplar isyan etti.<br>• <b>Sonuç:</b> Osmanlı tarafından bastırıldı AMA tamamen söndürülemedi.<br>• <b>Tarihi Önem:</b> ⭐ Bu, Balkan halklarının bağımsızlık hareketinin ilk ciddi denemesidir. 19. yüzyıl boyunca Balkan isyanları araya araya devam edecektir. Osmanlı artık Balkanları 'rahatça' yönetecek gücü kaybetmiştir.",
    
    "⚔️ <b>1806: OSMANLI-RUS SAVAŞI - FRANSA'NIN KIŞKIRTMASI:</b><br>• <b>Başlangıç:</b> Osmanlı-Rus savaşı Fransızların gazı ve teşviki ile başladı.<br>• <b>Siyasi Oyun:</b> Napolyon, Rusya'yı Osmanlı ile çatıştırmak istiyordu. Böylece Rusya'nın gücü azalacak, Napolyon'un Doğu'daki pozisyonu güçlenecekti.<br>• <b>Osmanlı'nın Pozisyonu:</b> Bilinçsizce başkasının oyununa dahil olmıştır. Bu tuzak devletlerin Osmanlı üzerinde nasıl oynayabileceğinin en açık örneğidir.",
    
    "🤝 <b>1807: TİLSİT ANTLAŞMASI - OSMANLIYA HİN KESİLMESİ:</b><br>• <b>Antlaşmanın Tarafları:</b> Rusya ile Fransa arasında imzalandı. <b>Osmanlı'nın bilgisi dışında!</b><br>• <b>Antlaşmanın Kapsamı:</b> Rusya ve Fransa kendi aralarında anlaştılar, düşmanlığı sona erdirdiler.<br>• <b>Osmanlı'ya Etkisi:</b> ⭐ Osmanlı Devleti tamamıyla yalnız kaldı. Ne Rusya'dan ne Fransa'dan dış destek alabilir hale geldi. Bu, 19. yüzyıl Osmanlı dış politikasının en kritik anlarından biridir.<br>• <b>Dersin Morali:</b> Güçlü devletler Osmanlı'nın başını döneceği kadar çatışırlarken, Osmanlı'nın kendi iç reformları bile yetersiz kalıyordu.",
    
    "🇬🇧 <b>1809: İNGİLTERE VE 'KALE-İ SULTANİYE' ANTLAŞMASI - BATIYA SIRAÇ OLMA:</b><br>• <b>Antlaşma:</b> İngiltere ile Osmanlı Devleti arasında 'Çanakkale (Kale-i Sultaniye)' Antlaşması imzalandı.<br>• <b>İçeriği:</b> İngiltere Osmanlı'ya dostluk ve ticari imtiyazlar vereceğini vaad etti.<br>• <b>Gerçek Anlam:</b> Osmanlı bunca zamandır Batı'ya kapı açıyordu, şimdi açık kapıdan giren İngiltere ile resmi ilişkiler kuruyor. Başta Çanakkale (boğazlar) üzerindeki İngiliz nüfuzu başlıyor.",
    
    "🇷🇺 <b>1812: BÜKREŞ ANTLAŞMASI - BALKAN HALKLARINA İLK İMTİYAZ:</b><br>• <b>Antlaşmayı İmzalayanlar:</b> Osmanlı Devleti ve Rusya<br>• <b>Kritik Madde:</b> Sırplar bu antlaşma ile <b>ilk imtiyaz elde eden millet olmuştur.</b> ⭐<br>• <b>Sırpların Kazanması:</b> Oto nomisi (bağımsız yönetim hakkı), vergi muafiyeti ve dinî özgürlük.<br>• <b>Tarihsel Kırılma:</b> Bu antlaşma, Balkanlıların artık Osmanlı egemenliğini tamamen kabul etmeyeceğini, uluslararası destek ile haklarını talep edeceğini gösterir. Böylece Balkan sorunu başlamıştır ve 19. yüzyıl boyunca devam edecektir.",
    
    "🎭 <b>1815: VİYANA KONGRESİ - AVRUPA'NIN YENİDEN ŞEKİLLENMESİ VE 'ŞARK SORUNU'NUN DOĞUŞU:</b><br>• <b>Kimin Başkanlığında:</b> Avusturya Başbakanı Metternich<br>• <b>Amaç:</b> Napolyon'un yıkılmasından sonra Avrupa'nın siyasî haritasını yeniden düzenlemek.<br>• <b>Osmanlı ve Şark Sorunu:</b> <b>İlk defa burada Rus Çarı Aleksandr 'Şark Sorunu'nu resmî olarak dile getirdi.</b> ⭐ Şark Sorunu = Osmanlı Devleti'nin geleceğinin ne olacağı? Nasıl paylaştırılacak? Kim kontrol edecek?<br>• <b>Kongrenin Genel Kararları:</b><br>   ○ Dünyanın her yerinde çıkan milliyetçilik isyanları bastırılacak (Osmanlı'nın Balkan sorunlarının temelini atar)<br>   ○ Fransa'nın ortadan kaldırdığı krallıklar yeniden kurulacak<br>   ○ Avrupa siyasî haritası eski düzene dönecek<br>• <b>Osmanlı Açısından:</b> Osmanlı bu kongreye davet edilmemiştir! Kararlar Osmanlı'nın dışında, onun üzerine alınmıştır. Bu, 19. yüzyıl Osmanlı politikasının özetini verir: Osmanlı yapılan kararların alıcısı, kaynağı değildir.",
    
    "⏳ <b>1815-1827: RESTORASYONn DÖNEMİ (Viyana Kongresi'nden Navarin Olayı'na):</b><br>• <b>Nedir:</b> Fransa'nın çıkardığı kaostan sonra Avrupa'nın 'eski düzene dönmeye' çalıştığı dönemdir.<br>• <b>Osmanlı İçin Anlam:</b> Bir ara nefes alma dönemidir. Ancak bu nefes çok kısa sürecek...",
    
    "🔗 <b>1820: FİLİKİ ETERİA CEMİYETİ'NİN KURULMASI - YUNAN İSYANININ HAZIRLANMASI:</b><br>• <b>Kurucu:</b> Rus Generali Aleksandr İpsilanti<br>• <b>Amacı:</b> Osmanlı topraklarında Rumlar ve Balkan halklarını bağımsızlığa hazırlamak.<br>• <b>İlk Hareketi:</b> 1820'de Eflak'ta Rumlar ayaklanması başladı, ancak bastırıldı.<br>• <b>Tarihi Anlam:</b> ⭐ Bu cemiyet gizli bir devlet dış politikası aracıdır. Rusya, Osmanlı Devleti'nin içinde 'yürüyüşçü' birlikleri oluşturmuştur.",
    
    "🔴 <b>1821: MORA YUNAN İSYANI - 19. YÜZYIL BALKAN KARGAŞASININ BAŞLANGICI:</b><br>• <b>Olay:</b> Mora (Peloponnesos) bölgesinde Yunan isyanı başladı.<br>• <b>Sonuç:</b> Tripolice Katliamı gerçekleşti. Osmanlı askerlerinin ve Türk civvarı'nın katledilmesi.<br>• <b>Yunan İsyanı'nın Çıkış Sebepleri:</b><br>   ○ <b>Milliyetçilik Akımı:</b> Avrupa'da 19. yüzyıl başında ulusçuluk (milliyetçilik) trendi başladı. Rumlar da bu rüzgara kapıldı.<br>   ○ <b>Avrupalıların Kışkırtması:</b> İngiltere ve Fransa, romantik dönem nedeniyle antik Yunan'a hayranlık duyuyordu. Söylemli 'Yunan medeniyetini kurtaralım' dediler.<br>   ○ <b>Rum Aydınları ve Din Adamları:</b> Patriarh ve aydın Rumlar bağımsızlık fikrini yayıyordu.<br>   ○ <b>Filiki Eterya Cemiyeti:</b> Gizlice bağımsızlık için hazırlık yapıyordu.<br>   ○ <b>Eski Bizans Nostalji:</b> Rumlar 'eski Bizans İmparatorluğu'nu yeniden kurmak istiyorlardı.<br>   ○ <b>Tepedelenli Ali Paşa'nın Durumu:</b> Yanya Valisi Tepedelenli Ali Paşa kendi isyanını yapmıştı ve Osmanlı askerlerini meşgul etmişti. Bu, Yunanlara isyan fırsatını verdi.<br>• <b>II. Mahmut'un Pozisyonu:</b> II. Mahmut başta Yunan İsyanı ile yeterince ilgilenemedi, çünkü Tepedelenli Ali Paşa'nın isyanını öncelikle bastırmak zorundaydı. ⭐<br>• <b>İsyanı Kim Bastırdı:</b> Mısır Valisi Mehmet Ali Paşa donanma gönderdi. Ancak isyanı bastırdıktan sonra Mehmet Ali Paşa donanmasını Mısır'a geri çekti.",
    
    "🛢️ <b>1827: NAVARİN OLAYII - AVRUPA'NIN AÇIK MÜDAHALESİ VE RESTORASYONUNa SON:</b><br>• <b>Olay:</b> İngiltere, Fransa ve Rusya Yunanlılara bağımsızlık verilmesini talep etti. Osmanlı Devleti bunu reddettiği için, bu üç gücün Osmanlı donanması (Mısır donanması) Navarin Limanı'nda yakıldı.<br>• <b>Kritik Anlama:</b> ⭐ <b>Bu olay, Restorasyon Dönemi'nin resmen sona erişini gösterir.</b> Artık Avrupa devletleri Osmanlı Devleti'ne karşı açıkça mücadele edecektir.<br>• <b>Osmanlı'nın Durumu:</b> Osmanlı Devleti, kendi topraklarında bulunan bir donanmaya karşı savunmasız kaldı. Avrupa devletleri kendi aralarında anlaştığında, Osmanlı tek başına karşı koyamıyor.",
    
    "⚔️ <b>1827-1828: OSMANLI-RUS SAVAŞI - AVRUPA'NIN SONUCU DEĞİŞTİRMESİ:</b><br>• <b>Savaş Sonucu:</b> Rusya kazandı, Osmanlı kaybetti.<br>• <b>Stratejik Anlam:</b> Osmanlı kendi savaşında kaybetti, ancak savaşta Rusya'ya karşı İngiltere ve Fransa tarafından desteklenmedi. Bu, uluslararası dengelerin Osmanlı aleyhine döndüğünü gösterir.",
    
    "📋 <b>1829: EDİRNE ANTLAŞMASI - BALKAN'DA BİRBİRİNE FARKLI STATÜLER:</b><br>• <b>Antlaşmanın Maddeleri:</b><br>   ○ <b>Sırplar:</b> Özerk devlet (semi-independent) hale geldi. Tamamen bağımsız değil, ama yarı-bağımsız.<br>   ○ <b>Yunanlılar:</b> Tamamen bağımsız devlet olarak tanındı. ⭐<br>• <b>Tarihsel Kırılma:</b> Bu antlaşma sonrası Balkanlar artık Osmanlı'nın tek hâkimi olmadı. Bölge bir 'çoklu statüler bölgesi' haline geldi. Her bölgenin farklı derecede bağımsızlığı olacak.",
    
    "🇫🇷 <b>1830: FRANSA CEZAYIR'İ İŞGAL ETTİ - KUZEY AFRİKA'DAKİ İLK KAYıP:</b><br>• <b>Olay:</b> Fransa Osmanlı topraklarından Cezayir'i işgal etti ve ilhak etti.<br>• <b>Tarihi Önem:</b> ⭐ <b>Bu, Osmanlı Devleti'nin Kuzey Afrika'da ilk büyük toprak kaybıdır.</b> Bundan sonraki 50 yılda Tunus, Mısır, Libya hep kaybedilecektir.",
    
    "🐪 <b>1833: MEHMETa ALİ PAŞA KRİZİ VE KÜTAHYA ANTLAŞMASI - OTTOMAN'IN EN TEHLİKELİ İÇ SORUN:</b><br>• <b>Nedeni:</b> Mora İsyanı'nı bastırdığı için Mora valiliğini istedi Mehmet Ali Paşa, ancak II. Mahmut bunu vermedi. Bunun yerine sadece Mısır valiliğini sundu.<br>• <b>Mehmet Ali Paşa'nın Tepkisi:</b> Bunu reddetti ve kendi oğlu İbrahim Paşa'nın komutasında bir ordu göndererek Kütahya'ya kadar ilerledi!<br>• <b>Kütahya Antlaşması (1833):</b> Mehmet Ali Paşa'ya kazandırdığı ödüller:<br>   ○ Mısır valiliğine ek olarak <b>Girit valiliği</b><br>   ○ <b>Şam valiliği</b> (Suriye)<br>   ○ Oğlu İbrahim Paşa'ya <b>Cidde</b> ve <b>Adana</b> muhassılığı<br>• <b>Tarihsel Sonuç:</b> ⭐ Mehmet Ali Paşa fiilen Mısır ve Suriye'nin hâkimi haline gelmiştir. Osmanlı Devleti merkezi iktidara ihtiyat duyduğu için, bölgesel bir emirn boyunluğa rıza göstermiştir.",
    
    "🤲 <b>1833: 'DENİZE DÜŞEN YILAN SARILIR' - HÜNKÂR İSKELESİ ANTLAŞMASI:</b><br>• <b>Dramı:</b> İngiltere ve Fransa, Osmanlı'yı Mehmet Ali Paşa krizi'nde desteklemediler. Osmanlı yalnız kaldı.<br>• <b>Osmanlı'nın Çare Yolu:</b> Eski düşmanı Rusya'ya sarılmak zorunda kaldı. <b>'Denize düşen yılan sarılır'</b> tarzı bir hareket.<br>• <b>Antlaşmanın İçeriği:</b> Rusya ile 8 yıllığına barış antlaşması.<br>• <b>Gizli Madde:</b> ⭐ Bir savaş çıkırsa Osmanlı boğazları Rus donanmasına açacak, ancak hiçbir başka devletin donanmasını geçirtmeyecektir. (Böylece Rusya tek başına Akdeniz'e girmişti!)<br>• <b>Boğazlar Sorunu'nun Doğuşu:</b> ⭐ <b>Bu antlaşma ile BOĞAZLAR ilk defa uluslararası bir sorun haline gelmiştir.</b> Bundan sonra 19. yüzyıl boyunca Çanakkale ve İstanbul boğazlarının kontrolü Avrupa devletlerinin başlıca tartışma konusu olacaktır.",
    
    "🤝 <b>1838: BALTALİMANI ANTLAŞMASI - TİCARİ AÇILIM VE EKONOMIK BAĞIMLILIĞA BAŞLANGIC:</b><br>• <b>Taraflar:</b> İngiltere ve Osmanlı Devleti<br>• <b>Amacı:</b> Osmanlı Devleti, Mehmet Ali Paşa krizinin çözümü için İngiltere'nin desteğini almak istedi.<br>• <b>Antlaşmanın Maddeleri:</b><br>   ○ <b>İç gümrük vergisi kaldırıldı</b> (Osmanlı'nın kendi ülkesinde kendi malları üzerinden vergi alamaması!)<br>   ○ <b>İthalattan alınan vergi %12'den %5'e düşürüldü</b> (Avrupalı mal akışını kolaylaştırdı)<br>• <b>Sonuç:</b> ⭐ <b>Osmanlı Devleti resmen Avrupa'nın açık pazarı haline geldi!</b> Osmanlı'nın yerli üreticisi koruma görmedi, Avrupa malı ucuz girdi, ekonomik bağımlılık başladı.",
    
    "⚔️ <b>1839: NİZİP SAVAŞI - OSMANLI'NIN BAŞARISIZLIĞININ DAMGASI:</b><br>• <b>Savaşan Taraflar:</b> Osmanlı Devleti ve Mehmet Ali Paşa (Mısır Valisi)<br>• <b>Sonuç:</b> Osmanlı Devleti Nizip Savaşı'nda Mehmet Ali Paşa'ya karşı KAYBETTI.<br>• <b>Askeri Demokrasi:</b> Osmanlı ordusunun kendi içindeki biri (Mehmet Ali) tarafından yenilmesi Osmanlı'nın ne kadar çöktüğünü göstermektedir.",
    
    "📢 <b>1840: LONDRA KONFERANSı - MEHMETa ALİ SORUNU ULUSLARAARASILAŞTIRILMESİ:</b><br>• <b>Amaç:</b> Mehmet Ali Paşa sorununun çözümlenmesi.<br>• <b>Kritik Unsur:</b> Fransa bu konferansta yer almadı, çünkü Fransa Mehmet Ali Paşa'yı destekliyordu!<br>• <b>Kararlar:</b> İngiltere, Rusya, Avusturya ve Prusya Mehmet Ali Paşa'yı desteklemedi, sadece Osmanlı'yı desteklediler.<br>• <b>Osmanlı'nın Tepkisi:</b> Osmanlı bu Konferans'ta kendini savunmak, güç göstermek için <b>Tanzimat Fermanı</b> ilan etti. (Reform yapıyoruz, modern devlet oluyoruz mesajı verdi.)<br>• <b>Tarihsel Dönüm Noktası:</b> ⭐ Bir <b>iç mesele olan Mısır sorunu uluslararası bir soruna dönüştü.</b> Artık Osmanlı'nın sınırları içindeki sorunlar bile Avrupa devletlerinin izni ile çözülecektir.",
    
    "📜 <b>1840: TANZIMAT FERMANININ İLANı - OSMANLIYA'NIN MODERN OLUŞ ÇABASI:</b><br>• <b>Nedir:</b> Osmanlı Devleti'nde modern devletleşme reformlarının başlangıcıdır.<br>• <b>Amaç:</b> Londra Konferans'ındaki Avrupa devletlerini ikna etmek ve Osmanlı'nın çağdaş bir devlet olduğunu göstermek.<br>• <b>Sonuç:</b> Reformlar yapılacak, ancak Avrupa devletlerinin denetimi altında.",
    
    "🚢 <b>1841: LONDRA BOĞAZLAR SÖZLEŞMESİ - BOĞAZLAR SORUNUN ULUSLARARASALA:</b><br>• <b>Antlaşmayı İmzalayanlar:</b> Osmanlı, İngiltere, Fransa, Rusya, Avusturya, Prusya<br>• <b>Amaç:</b> Boğazlar meselesi uluslararası bir sorun olmuş, çözümü için 6 gücün katılımı gerekmiştir.<br>• <b>Kararlar:</b> Barış zamanında hiçbir yabancı donanma Boğazlar'dan geçemeyecek. Savaş zamanında Osmanlı hangi devleti desteklerse, o devletin donanması geçebilecek.<br>• <b>Osmanlı Açısından:</b> ⭐ Boğazlar artık Osmanlı'nın tamamen özerkliğinde değil, uluslararası bir statüsü olan bölge haline gelmiştir.",
    
    "⚔️ <b>KIRIM SAVAŞI ÖNCESİ (1853) - OSMANLIYA'NIN TEHLIKELI YALNIZLIĞI:</b><br>• <b>Durum:</b> Osmanlı Devleti kendini Rusya ile doğrudan çatışmaya yakın bulmuştur.<br>• <b>Osmanlı'nın Çare Arayışı:</b> İngiltere ve Fransa'nın desteğini almak zorundadır. Aksi halde Rusya Osmanlı'yı istediği gibi parçalayacaktır.",
    
    "🔫 <b>1853-1856: KIRIM SAVAŞI - OSMANLIYA'NIN SON ZAFER SAVAŞı VE BORÇLANMASI:</b><br>• <b>Savaşan Taraflar:</b><br>   ○ <b>Bir Taraf:</b> Osmanlı (İngiltere ve Fransa desteğinde)<br>   ○ <b>Diğer Taraf:</b> Rusya<br>• <b>Savaş'ın Çıkış Nedenleri:</b><br>   ○ <b>Osmanlı Donanmasının Sinop'ta Yakılması (1853):</b> Rus donanması Osmanlı donanmasını Karadeniz'de yaktı. Bu, Osmanlı'nın ne kadar zayıf olduğunun kanıtı.<br>   ○ <b>Rus Elçisi Mençikov'un İstekleri:</b> Rusya Osmanlı'da ayrıcalıklı statü talep etti.<br>   ○ <b>Kutsal Yerler Sorunu:</b> Rusya Kudüs'teki Kutsal Mekanlar üzerinde denetim talep etti. (Dini bir gerekçe ile siyasî genişleme)<br>   ○ <b>Macar ve Leh Mülteci Sorunu:</b> Macar ve Leh devrim kaçaklarını Osmanlı'ya sığınmasına Rusya kızıyor.<br>   ○ <b>Hünkâr İskelesi Antlaşması'nın Geri Alınması:</b> Rusya 1833'ten beri boğazları kontrol etme hakkını kendi adına yaşatmak istiyordu.<br>• <b>Savaş Sırasında Önemli Olaylar:</b><br>   ○ <b>Florence Nightingale - Hemşireliğin Kurucusu:</b> İngiliz ve Osmanlı askerlerini <b>Levent ve Selimiye Kışlaları</b>'nda tedavi etti. ⭐ Bu kışlalar III. Selim döneminde kurulan askerî tesislerdir.<br>   ○ <b>İlk Dış Borç:</b> Osmanlı Devleti Kırım Savaşı sırasında tarihinde ilk defa dış borç aldı (İngiltere'den, Sultan Abdülmecid adına).<br>   ○ <b>İlk Telgraf Hattı:</b> Savaş sırasında ilk defa Kırım-Varna-Edirne (İstanbul-Şumnu-Edirne) arasında telgraf hattı çekildi. Modern haberleşme başladı.",
    
    "✌️ <b>1856: PARİS BARIŞ KONFERANSI VE ANTLAŞMASI - OSMANLIVA'NIN AVRUPA'YA SORULACAK DEĞİŞMESİ:</b><br>• <b>Konferansın Tarafları:</b> Osmanlı, İngiltere, Fransa, Rusya, Avusturya, Prusya vb.<br>• <b>Antlaşmanın Maddeleri:</b><br>   ○ <b>Osmanlı Devleti'nin toprak bütünlüğünü Avrupa devletleri koruyacak:</b> AMA Osmanlı tek başına koruyamayacağı anlaşıldı! Yani Osmanlı güç gösteremez hale gelmiştir.<br>   ○ <b>Osmanlı Devleti Avrupa hukuku'ndan faydalanacak:</b> Batı hukuk sistemine uyum.<br>   ○ <b>Osmanlı Devleti bir Avrupa devleti sayıldı:</b> ⭐ Uluslararası camiada meşruiyeti sağlanmak istendi. AMA bu, Osmanlı'nın Avrupa'ya tam bağımlılığını da anlama geliyordu.<br>   ○ <b>Hem Osmanlı hem Rusya Karadeniz'de tersane ve donanma bulunduramayacak:</b> Karadeniz'in demilitarizasyonu. (Burada Rusya çok kaybetti, Osmanlı da.)<br>   ○ <b>Osmanlı Devleti yenik bir devlet muamelesi gördü:</b> ⭐ Resmi olarak Osmanlı Avrupa tarafından galip değil, mağlubun konumunda kabul edilmiştir!<br>• <b>Osmanlı'nın Tepkisi:</b> Kararlara etkili olmak için <b>Islahat Fermanı</b> yayımladı (bir dahaki reformun habercisi).",
    
    "💪 <b>İSLAHAT FERMANININ İLANı (1856) - BATIYA UYUM ÇABASı:</b><br>• <b>Nedir:</b> Tanzimat'ı derinleştiren, Osmanlı yönetim sistemini daha da Batılılaştıran bir ferman.<br>• <b>Tarihsel Anlam:</b> Osmanlı artık kendi uygunluğu için değil, Batı'nın baskısı altında reform yapıyor.",
    
    "🔥 <b>1875: BALKAN BUNALIMI - 19. YÜZYIL OSMANLYA'NIN EN KRITIK İÇ KRIZISI:</b><br>• <b>Nedir:</b> Balkan'daki isyanlar Osmanlı'nın kontrol alanı dışına çıktı.<br>• <b>İsyanlar Yayıldı:</b> Bulgaristan, Sırbistan, Karadağ ve Arnavutluk aynı anda isyan etti.<br>• <b>Osmanlı'nın Durumu:</b> Çok zayıf olduğu için tüm bu isyanları aynı anda bastıramadı. Osmanlı başında olan İmparatorluğun çıkışı bu olay ile başlıyor.",
    
    "🏛️ <b>1876: TERSANE KONFERANSı - OSMANLIYA'NIN SON REFORMU VE İLK ANAYASASI:</b><br>• <b>Amaç:</b> Balkan sorununu uluslararası konferansa götürerek çözmek. Aynı zamanda Balkan halklarının isyanını bastırmamak, hukuki çerçevede çözmek.<br>• <b>Konferans Sırasında:</b> <b>I. MEŞRUTIYET (1876) ilan edildi!</b> ⭐<br>   ○ <b>Bu Nedir:</b> Osmanlı tarihinde ilk anayasa. Padişah'ın mutlak iktidarını sınırlayan, meclisi kurulan, meşruti monarşi sistemi.<br>   ○ <b>Tarihçe:</b> Mithat Paşa tarafından hazırlanmış. Osmanlı'nın Batı'daki kamuoyunun desteğini almak istediğini göstermek amaçlı.<br>• <b>İngiltere'nin Pozisyon Değişimi:</b> ⭐ <b>Osmanlı Devleti'nin toprak bütünlüğünü koruyan İngiltere bu politikadan VAZGEÇTÎ!</b> Çünkü İngiltere Rusya'nın Akdeniz'e inmesini engellemek için değil, artık Osmanlı'nın parçalanması ile ilgilenmiye başlamıştı (Kıbrıs, Mısır gibi alanlar).",
    
    "⚔️ <b>1877-1878: 93 HARBI (OSMANLI-RUS SAVAŞI) - OSMANLIVA'NIN TOPRAK KAYBININ BAŞLANGICI:</b><br>• <b>Harp Komutanları:</b><br>   ○ <b>Batı Cephesi:</b> Gazi Osman Paşa (Plevne Kahramanı) - Plevne'de 143 gün direnç gösterdi!<br>   ○ <b>Doğu Cephesi:</b> Gazi Ahmet Muhtar Paşa<br>   ○ <b>Halk Kahramanı:</b> Nene Hatun (Uzunçarşılı Nene Hatun)<br>• <b>Savaş'ın Sonucu:</b> Osmanlı kaybetti, Rusya kazandı.<br>• <b>Osmanlı'nın Durumu:</b> Hem Plevne'de direnç gösterse de, genel olarak Osmanlı ordusunun kapasitesi kalmamıştır. 19. yüzyıl askeri reformları yeterli olmamıştır.",
    
    "📋 <b>1878: AYASTEFANOS ANTLAŞMASI - OSMANLIVA'NIN EN KÖTÜ ANTLAŞMASI (IMZALANDI AMA YÜRÜRLÜĞE GİRMEDİ):</b><br>• <b>Maddeleri:</b><br>   ○ Bulgaristan bağımsız devlet olacak<br>   ○ Sırpistan, Karadağ, Romanya bağımsız olacak<br>   ○ Osmanlı Rumeli'nin büyük kısmını kaybedecek<br>   ○ Rusya Doğu Anadolu bölgelerini (Kars, Ardahan) alacak<br>• <b>Neden Yürürlüğe Girmedi:</b> Avusturya ve İngiltere bunu protesto ettiler. Özellikle İngiltere, Rusya'nın çok fazla toprak almasını istemiyor. (Dünya dengesi bozulacak diye düşündü.)",
    
    "🎯 <b>1878: BERLİN ANTLAŞMASI - OSMANLIVA'NIN TOPRAKLARININ BÖLÜŞTÜRÜLDÜĞÜ ANTLAŞMA:</b><br>• <b>Başkan:</b> Alman Başbakanı Bismarck<br>• <b>Katılanlar:</b> Osmanlı, Rusya, İngiltere, Fransa, Avusturya, İtalya, Almanya<br>• <b>Antlaşmanın Maddeleri:</b><br>   ○ <b>Bulgaristan 3'e Bölünecek:</b><br>      • 1. Bulgar Prensliği (bağımsız)<br>      • 2. Doğu Rumeli Devleti (Osmanlı'ya bağlı otonom devlet)<br>      • 3. Makedonya (Osmanlı'da kalacak) - ⭐ En büyük sorun burası<br>   ○ <b>Rusya'nın Akdeniz'e İnmesi Engellendi:</b> Karadeniz'deki genişlemesi sınırlandırıldı. (Kars, Ardahan, Batum aldı, ama Bulgaristan'ı tamamen alamadı)<br>   ○ <b>Sırbistan, Karadağ, Romanya Bağımsız Olacak</b><br>   ○ <b>Bosna-Hersek:</b> Osmanlı'ya bağlı kalacak AMA <b>Avusturya tarafından yönetilecek!</b> ⭐ Bu, Osmanlı egemenliğinin simülatörü olmuştur. Avusturya fiilen Bosna'yı işgal etti.<br>   ○ <b>Girit ve Doğu Anadolu'da Ermeniler İçin İslahat:</b> <b>Ermeni Meselesi burada uluslararası boyuta çıktı!</b> ⭐ Osmanlı Devleti'nin Ermeni azınlığına yönelik ne yapacağı artık Avrupa devletlerinin denetimi altındadır.<br>   ○ <b>Kars, Ardahan, Batum Rusya'ya (Elviye-i Selase):</b> Osmanlı Doğu'da bu üç şehri kaybetti. Ancak <b>Doğu Beyazıt Osmanlı'da kaldı.</b><br>• <b>Genel Sonuç:</b> ⭐ <b>Berlin Antlaşması ile Osmanlı Devleti Rumeli'nin çoğunu kaybetti. Artık Balkan'da Osmanlı sadece Makedonya, Kosova ve başlı-başına bölgelerde varlık gösterir.</b>",
    
    "🎟️ <b>1878: KÜBRIS'İN İDARESİ VE HALEP FERMANI:</b><br>• <b>Kıbrıs:</b> Berlin Antlaşması öncesi, İngiltere ile yapılan gizli anlaşmada Kıbrıs'ın idaresi İngiltere'ye bırakılmıştır. (Osmanlı egemenliği kalır, yönetim İngiltere'de)<br>• <b>Halep Fermanı (1878):</b> Giritli Rumları için yayımlanan ferman. AMA bunun etkisi sınırlı olmuştur.",
    
    "🌍 <b>1881-1882: TUNUS VE MISIR'IN KAYBEDILMESI - KUZEY AFRİKA'NIN TAMAMEN GITMESI:</b><br>• <b>1881: Fransa Tunus'u İşgal Etti</b><br>• <b>1882: İngiltere Mısır'ı İşgal Etti</b><br>• <b>Tarihsel Sonuç:</b> ⭐ Osmanlı Devleti artık Kuzey Afrika'da neredeyse hiç varlık göstermemektedir. (Sadece Trablusgarb ve Bingazi küçük vilayet olarak kalır.)<br>• <b>Osmanlı'nın Durumu:</b> Bir zamanlar Akdeniz'in seçkin gücü olan Osmanlı, 19. yüzyılın sonunda Balkan'da ve Anadolu'da sıkışmış durumdadır.",
    
    "🇬🇷 <b>1897: DOMOKE MEYDAN SAVAŞI - OSMANLIVA'NIN SON BAŞARILI SAVAŞI:</b><br>• <b>Karşı Taraf:</b> Yunanistan<br>• <b>Sonuç:</b> Osmanlı kazandı! ⭐<br>• <b>Ama Önemli Not:</b> Bu, Osmanlı'nın toprak kaybetmeyi durduran değil, sadece son başarısıdır.<br>• <b>Mustafa Kemal'in Anısı:</b> M. Kemal bu savaşa katılmak istedi ve sonradan şöyle dedi: <b>'Gençliğimin en heyecan verici günleriydi.'</b> Bu savaş, genç Kemal'i askerliğe iten olaylardan biridir.",
    
    "🎓 <b>XIX. YÜZYIL OSMANLYA'NIN GENEL CHARACTERİZASYONU (ÖZET):</b><br>• <b>Siyasal Davraniş:</b> Osmanlı Devleti 19. yüzyılda başında hareketli, dinamik ama de facto kontrolü azalan bir devlettir.<br>• <b>Ekonomik Durum:</b> Baltalimanı ve sonrası ticari antlaşmalar ile Osmanlı açık pazarı haline gelmiştir. Yerli ekonomi, tarım ve zanaat sektörleri çökmüştür.<br>• <b>Siyasi Yapı:</b> Merkezi iktidarsızlığa gidişat söz konusu. Bölgesel valiler (Mehmet Ali) serbest davranmıştır.<br>• <b>Askerî Yapı:</b> 18. yüzyıl reformları (Nizam-ı Cedid) başarısız olmuş, 19. yüzyıl islahat yeterli olmamıştır. Osmanlı ordusunun teknolojisi ve eğitimi Avrupa standartlarının gerisinde kalmıştır.<br>• <b>Uluslararası Pozisyon:</b> Osmanlı artık bir oyuncu değil, oynanılan bir tahtadır. Kararlar Osmanlı'nın dışında alınır.<br>• <b>Tarafların Açlığı:</b> Rusya Osmanlı'yı ele geçirmek istiyordu (Şark Sorunu), İngiltere Osmanlı'nın parçalanmasını kontrol etmek istiyordu, Avusturya Balkan'dan pay istiyordu, Fransa Kuzey Afrika'yı istiyordu.",
    
    "⚠️ <b>XIX. YÜZYIL SONUNDA OSMANLYA'NIN HARITASI:</b><br>• <b>Anadolu:</b> Hâlâ Osmanlı kontrolünde, AMA batı vilayetleri gücü azalmıştır.<br>• <b>Balkan'lar:</b> Büyük orta-kuzey kısmı gitti. Makedonya, Kosova, kuzey kısımlar kalmıştır.<br>• <b>Kuzey Afrika:</b> Cezayir (1830), Tunus (1881), Mısır (1882) gitti. Sadece Trablusgarb ve Bingazi kalıştır.<br>• <b>Körfez Bölgesi:</b> Hâlâ Osmanlı kontrolünde, AMA Britanya nüfuzu arttırmıştır. (Petrol bulunacak bilinmese de, stratejik konumu önemlidir.)<br>• <b>Ermenistan ve Doğu Anadolu:</b> Rusya Kars, Ardahan, Batum'u aldı. Ermeni sorunu Avrupa devletlerinin denetimi altına girdi.",
    
    "🎪 <b>NİHAYET: 'AVRUPA'NIN HASTASı' - OTTOMAN'IN İFADESİ:</b><br>• <b>Terim:</b> 19. yüzyılda Avrupa devletleri Osmanlı Devleti'ni 'Avrupa'nın Hastalı Adamı' olarak adlandırmaya başladılar.<br>• <b>Anlamı:</b> Osmanlı ölmek üzere olan, parçalanması beklenen bir devlet olarak görülüyordu.<br>• <b>Çürüyen Kısım:</b> Balkan'lar, kuzey Afrika, azınlıklar sorunları.<br>• <b>Sağlık Kalabilirsek:</b> Anadolu ve merkezi yapı, ancak bu da kısa süre sonra sarsılacaktır (20. yy başında).<br>• <b>Sonuç:</b> I. Dünya Savaşı'na grilecek olan Osmanlı Devleti artık 19. yüzyılın sonunda iyileşme şansı kalmamıştır. Tarih yazılmıştır."
];