// notlar/tarih-8-not.js
window.tarih_8_notlari = [
    "🌍 <b>AVRUPA'NIN GENEL DURUMU:</b><br>• <b>Makyavelizm:</b> Avrupa devletlerinin amaca ulaşmak için her türlü tedbire başvurması.<br>• <b>Fransa:</b> 7 Yıl Savaşları'nı kaybetti, sömürgeleri İngiltere'ye geçti, ihtilal yaşandı, dönem sonunda Mısır'a saldırdı.<br>• <b>Avusturya:</b> Rusya ile işbirliği, Balkanlara egemen olmayı hedefledi, Ege Denizi'ne ulaşmak istedi.<br>• <b>Rusya (Çar I. Petro'nun Amaçları):</b> Kırım'ı alıp Karadeniz'e inmek, Akdeniz'e inmek, Orta Asya ve Kafkasya'ya ulaşmak, Balkanlarda Slav birliğini sağlamak.",
    
    "📋 <b>AVRUPALILARIN HAZIRLADIĞI PROJE PLANLAR:</b><br>• <b>Dakya Planı:</b> Rusya ve Avusturya'nın planıdır. Eflak ve Boğdan'da Dakya adında bir devlet kurulacak.<br>• <b>Grek Planı:</b> Rus prensi Potyomkin tarafından hazırlandı. İstanbul merkezli bir Rus devleti kurularak Bizans'ı tekrar canlandırmak amaçlanmıştır. (Doğu Sistemi'nin en büyük planı)",
    
    "⚔️ <b>KRİTİK SAVAŞ VE ANTLAŞMALAR (1711-1774):</b><br>• <b>1711 - Prut Antlaşması (Rusya ile):</b> Osmanlı kaybettiği toprakları geri alma umudu. Azak Kalesi Osmanlı'ya geri verildi.<br>• <b>1715-18 - Petrovaradin Savaşı (Avusturya ile):</b> Osmanlı kaybetti, bu savaş sonucunda Pasarofça Antlaşması'na gidildi.<br>• <b>1718 - Pasarofça Antlaşması (Avusturya ile):</b> ⭐ Osmanlı ilk defa Batı'nın üstünlüğünü kabul etti. LALE DEVRİ'NE GİRİŞ.<br>• <b>1736 - Belgrad Savaşı:</b> Osmanlı kazandı. Belgrad Antlaşması imzalandı (Fransa arabuluculuk yaptı).<br>• <b>1740 - I. Mahmut:</b> Kapitülasyonları sürekli hale getirdi.<br>• <b>1768-74 - Osmanlı-Rus Savaşı:</b> Ruslar Çeşme'de Osmanlı donanmasını yaktı.",
    
    "🏛️ <b>OSMANLI-VENEDİK İLİŞKİLERİ:</b><br>• <b>Mora Yarımadası'nın fethi tamamlandı.</b>",
    
    "🏛️ <b>OSMANLI-İRAN İLİŞKİLERİ:</b><br>• <b>1724 İstanbul Antlaşması:</b> Rusya ile İran paylaşılmıştır.<br>• <b>II. Kasr-ı Şirin (Kerden) Antlaşması:</b> İmzalanmıştır.",
    
    "🔥 <b>KÜÇÜK KAYNARCA ANTLAŞMASI (1774) - DÖNÜM NOKTASI:</b><br>• <b>Kırım bağımsız oldu.</b> ⭐ İlk defa tamamı Müslüman olan bir bölge Osmanlı'nın elinden çıktı.<br>• <b>Kırım dini açıdan Osmanlı Padişahına ait olacak.</b> ⭐ İlk defa halifelik siyasi bir güç olarak kullanıldı.<br>• <b>Rusya İstanbul'da daimi elçi bulunduracak</b> ve Balkanlar'da istediği her yere konsolosluk açacak.<br>• <b>Osmanlı'dan savaş tazminatı ödenecek.</b> ⭐ Osmanlı Devleti'nde ilk tazminat.",
    
    "📍 <b>KIRIM BÖLGESİ SONRASI OLAYLAR:</b><br>• <b>1779 - Aynalıkavak Tenkihnamesi:</b> Şahin Giray'ın Kırım hanlığı olması kararlaştırıldı.<br>• <b>1787-1792 - Kırım Geri Alma Mücadelesi:</b> Osmanlı, Kırım'ı geri almak için Rusya ve Avusturya ile savaştı.<br>• <b>1791 - Ziştovi Antlaşması (Avusturya ile):</b> Avusturya savaştan çekildi.<br>• <b>1792 - Yaş Antlaşması (Rusya ile):</b> ⭐ Kırım'ın Rusya'ya ait olduğu KABUL EDİLDİ.<br>🎯 <b>ÖNEMLİ NOT: Küçük Kaynarca ile bağımsız oldu, Yaş ile Rusya'ya ait oldu.</b>",
    
    "🇫🇷 <b>1798 - FRANSA'YA KARŞI İLK DENGE POLİTİKASI:</b><br>• Mısır'a saldıran Fransa'ya karşı Osmanlı ilk defa denge politikası uyguladı.<br>• <b>Cezzar Ahmet Paşa,</b> Napolyon'u <b>Nizam-ı Cedid Ordusu</b> ile durdurdu.",
    
    "💫 <b>GENEL NOTLAR:</b><br>• <b>Düvelerin Tarihçe Sırası:</b> 17. yy = Duraklama, 18. yy = Gerileme, 19. yy = Dağılma.<br>• <b>18. yy'da I. Dünya Savaşı'na kadar büyük devletlere \"Düvel-i Muvazaa\" denmiştir.</b>",
    
    "🛠️ <b>XVIII. YY ISLAHATLARININ GENEL ÖZELLİKLERİ:</b><br>• <b>Batı örnek alındı.</b> Baskı ve şiddet yoluyla benimsetilmek istenmiştir.<br>• 17. yy'a göre <b>daha kalıcı olmuştur.</b><br>• <b>Hukuk haricinde</b> her alanda ıslahat yapılmıştır.<br>• <b>Saray, ulema ve asker</b> yapılanlara karşı çıkmıştır.",
    
    "👑 <b>XVIII. YY ISLAHATÇILARI (KOD: 3-1-3-1-3):</b><br>➡️ <b>III. Ahmet</b> → <b>I. Mahmut</b> → <b>III. Mustafa</b> → <b>I. Abdülhamit</b> → <b>III. Selim</b>",
    
    "🎨 <b>1) III. AHMET DÖNEMİ:</b><br><b>Edirne Olayı:</b> Şeyhülislam Feyzullah Efendi'nin İstanbul'u idare altına alması üzerine II. Mustafa Edirne'de yaşamaya başladı. Yeniçeriler (kapıkulları) ayaklanarak II. Mustafa'yı tahttan indirdi.<br><b>LALE DEVRİ (1718-1730):</b> Pasarofça Antlaşması ile başlar, Patrona Halil İsyanı ile sona erer.<br>• <b>Sadrazam:</b> Nevşehirli Damat İbrahim Paşa<br>• <b>Minyatürcü:</b> Levni<br>• <b>Şair:</b> Nedim<br>• <b>Kelimeyi ilk kullanan:</b> Yahya Kemal Beyatlı<br>❌ Avrupa örnek alındı AMA askeri ıslahat yapılmadı.",
    
    "📚 <b>LALE DEVRİ ISLAHATLAR (Kültür-Sanat-Teknoloji):</b><br>• <b>İbrahim Müteferrika ve Sait Efendi:</b> Macaristan'dan matbaa getirildi. <b>Batı'dan getirilen ilk yenilik!</b> (Dini eserler basması yasak)<br>• <b>Sait Efendi:</b> Avrupa'da turkuveri akımını başlattı.<br>• <b>İlk defa geçici elçilikler:</b> Viyana, Varşova, Moskova, Paris<br>• <b>28 Mehmet Çelebi:</b> Paris Sefaretnamesi (Batı'ya açılan ilk pencere)<br>• <b>Tercüme heyetleri kuruldu.</b><br>• <b>İran'dan çiçek aşısı getirildi.</b><br>• <b>Gerçek Davut Ağa:</b> Tulumbacılar (itfaiye) ocağı kuruldu.<br>• <b>Barok ve Rokoko mimari üslubu benimsendi.</b><br>• <b>Sadabad Sarayı:</b> Versay Sarayı örnek alınarak yapıldı.<br>• <b>Yalova'da kağıt imalathanesi, İstanbul'da çini ve kumaş imalathaneleri kuruldu.</b><br>🏛️ <b>NOT: Batı tarzında ilk eser III. Ahmet Çeşmesi, ilk batı tarzı cami Nuruosmaniye Camii'dir.</b>",
    
    "⚔️ <b>2) I. MAHMUT DÖNEMİ:</b><br>• <b>İlk defa batı tarzında askeri ıslahatlar yapıldı!</b> ⭐<br>• <b>İlk batı uzmanı:</b> Conte de Bonneval (Humbaracı Ahmet)<br>• <b>Hendesehane açıldı:</b> Batı tarzı ilk teknik okul<br>• <b>Kütüphaneler açıldı,</b> el yazma eserler toplandı.<br>🎯 <b>NOT: Osmanlı'da batı tarzında ıslahat yapılan ilk kurum Humbara Ocağı'dır.</b>",
    
    "🎓 <b>3) III. MUSTAFA DÖNEMİ:</b><br>• <b>Dönem İsimli Devlet Adamları:</b> Koca Ragıp Paşa, Baron de Tott, Cezayirli Gazi Hasan Paşa<br>• <b>1773 - Tersane Hendesehanesi açıldı.</b><br>• <b>Eşham Sistemi kanunlaştı.</b> (İç borçlanma) ⭐ İleride kağıt paraya geçişin temsilî aşaması<br>• <b>Sürat Topçuları Ocağı kuruldu.</b>",
    
    "🎖️ <b>4) I. ABDÜLHAMİT DÖNEMİ:</b><br>• <b>Dönem İsimli Devlet Adamları:</b> Cezayirli Gazi Hasan, Halil Hamit Paşa<br>• <b>Baron de Tott ıslahatları devam etti.</b><br>• <b>Eşham sistemi uygulanmaya başlandı.</b><br>• <b>1775 - Mühendishane-i Bahr-i Hümayun açıldı.</b> (Deniz Mühendis Okulu)<br>• <b>Cülus bahşişi verme geleneği kaldırıldı.</b><br>• <b>Ulufe alma hakkının alınıp satılmasını yasakladı.</b><br>• <b>İstihkam okulu açıldı.</b><br>🎯 <b>NOT: III. Mustafa döneminde getirilen Baron de Tott, Mühendishane-i Berr-i Hümayun'un açılmasında etkilidir.</b>",
    
    "🔴 <b>5) III. SELİM DÖNEMİ - NİZAM-I CEDİD (YENİ DÜZEN) ÇAĞI:</b><br>• <b>Tüm ıslahatlar \"Nizam-ı Cedid\" adıyla anılmıştır.</b> ⭐<br>• <b>Fransa örnek alındı.</b><br>• <b>Radikal yönde ıslahatlar yapıldı.</b><br>• <b>Dönemi Kabakçı Mustafa İsyanı ile sona erdi.</b>",
    
    "📜 <b>NİZAM-I CEDİD DÖNEMİNDE YAPILAN ISLAHATLAR:</b><br>• <b>İlk kalıcı elçilik Londra'ya açıldı.</b> (Yusuf Agah Efendi) ⭐<br>• <b>Meşveret Meclisleri aktif hale getirildi.</b> (Danışma meclisleri)<br>• <b>Bilim insanlarından layihalar istendi.</b> (Proje önerileri)<br>• <b>Yeniçerilere talim yapma zorunluluğu getirildi.</b> (İlk defa askeri eğitim)<br>• <b>Zahire Nazırlığı kuruldu:</b> Karaborsacılığın önüne geçmeye çalıştı.<br>• <b>Sarayın altın ve gümüşleri eritildi:</b> Hazineyi doldurmak için<br>• <b>Matbaa-i Amire kuruldu:</b> Devlet matbaası<br>• <b>Mühendishane-i Berri-i Hümayun kuruldu:</b> Kara Mühendis Okulu<br>• <b>Fransızca ilk yabancı resmi dil:</b> Sadece askeri okullarda<br>• <b>Levent ve Selimiye Kışlaları yapıldı.</b><br>• <b>Şeyhülislam'ın yetkileri kısıtlandı.</b> ⭐ Din-devlet ayrılığı adımı<br>• <b>Yerli malı teşvik edildi.</b><br>• <b>Nizam-ı Cedid Ordusu kuruldu.</b> Masrafı için <b>İrad-ı Cedid Hazinesi</b> kuruldu.<br>🎯 <b>NOT: Nizam-ı Cedid'in ilk ve son başarısı Napolyon'a karşı AKKA SAVUNMASI'dır.</b>"
];